### ISSUE TITLE
Improve the geo-spatial search/filtering/ordering filter backends

### ISSUE THREAD

**Issue by barseghyanartur** [barseghyanartur/django-elasticsearch-dsl-drf#10]
As continuation of the #4 

Elasticsearch supports two types of geo data:

```text
- geo_point fields, which support lat/lon pairs.
- geo_shape fields, which support points, lines, circles, polygons,
  multi-polygons etc.
```

The queries in this group are:

```text
- geo_shape query: Find document with geo-shapes which either intersect,
  are contained by, or do not intersect with the specified geo-shape.
+ geo_bounding_box query: Finds documents with geo-points that fall into
  the specified rectangle.
+ geo_distance query: Finds document with geo-points within the specified
  distance of a central point.
* geo_distance_range query: Like the geo_distance query, but the range
  starts at a specified distance from the central point.
+ geo_polygon query: Find documents with geo-points within the specified
  polygon.
```

Where:

```text
- : Not yet implemented
* : Won't be implemented. We're not going to support deprecated 
    features (such as geo-distance-range).
+ : Already implemented.

 All other features (marked as -) are meant to be supported.

**Comment by barseghyanartur** [comment]
@id13:

Wanna help? :)

**Comment by id13** [comment]
When you state `geo_shape` and `geo_point` are not yet implemented, you mean the serializers ?
To the best of my knowledge, both elasticsearch-dsl and django-elasticsearch-dsl support it.

The geo_shape queries are more complex than geo_point queries ([source](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-shape-query.html#_spatial_relations)), so I would like your input on how you want it to look like.

**Comment by barseghyanartur** [comment]
@id13:

Sorry for the inconvenience. I only meant the queries. At the moment, only ``geo_shape`` is left. It's indeed the most complex and I think it can wait a little. So, if you would want to help with something else, it would be great. Perhaps fill in some documentation gaps. I haven't documented the Geo-spatial features [much](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/advanced_usage_examples.rst#geo-spatial-features).
