### ISSUE TITLE
How do I test django-elasticsearch-dsl-drf Endpoints?

### ISSUE THREAD

**Issue by Miserlou** [barseghyanartur/django-elasticsearch-dsl-drf#104]
It looks like the values being returned during my test cases are incorrect, I'm not sure that ES is aware that tests should be independent of the normal index, and I don't think this is documented yet. I'd like to have correct values in my tests, but I'd also like to not have to destroy my real data to run the test suite.

Can you give me a quick rundown on how to set up up `dj-es-dsl-drf` tests?

**Comment by barseghyanartur** [comment]
It's documented here https://django-elasticsearch-dsl-drf.readthedocs.io/en/0.17.2/quick_start.html#settings
