### ISSUE TITLE
400 Error, Only Through DRF

### ISSUE THREAD

**Issue by Miserlou** [barseghyanartur/django-elasticsearch-dsl-drf#108]
I'm going nuts over this one! Any ideas?!

Works fine locally, but having some prod issues.

From the DRF logs:

```
data-refinery-log-group-circleci-staging log-stream-api-circleci-staging GET http://vpc-es-circleci-staging-xyz.us-east-1.es.amazonaws.com:80/experiments/doc/_search [status:400 request:0.014s]
data-refinery-log-group-circleci-staging log-stream-api-circleci-staging [pid: 21|app: 0|req: 8/11] 192.168.255.1 () {38 vars in 706 bytes} [Fri Jan 25 21:14:20 2019] GET /es/ => generated 27 bytes in 53 msecs (HTTP/1.1 500) 5 headers in 165 bytes (1 switches on core 7)
```

400 response from the server, but if I `wget` that exact same URL endpoint from the same server manually, I get my normal ES search response.

What could possibly be causing ES to 400 _only when it comes from DRF_?

**Comment by barseghyanartur** [comment]
@Miserlou:

It might be a cors issue.

https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html

See `http.cors.*` settings.

**Comment by barseghyanartur** [comment]
@Miserlou:

Can you specify command to run ES?

**Comment by Miserlou** [comment]
This is with AWS's hosted ES Service, so there is no command to run it: https://aws.amazon.com/elasticsearch-service/ No `elasticsearch.yml` or anything like that.

**Comment by barseghyanartur** [comment]
https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-createupdatedomains.html#es-createdomain-configure-ebs-cli

https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-createupdatedomains.html

**Comment by Miserlou** [comment]
Does `es-dsl`/`-drf` send an `Authorization` header? Ex:

```
curl http://vpc-es-circleci-staging-xyz.us-east-1.es.amazonaws.com:80/ -H "Authorization: lolwhat"
{"message":"Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. Authorization=lolwhat"}user@38c67d39b36e:~$
```

**Comment by barseghyanartur** [comment]
But, in short, I don't have experience with Elastic on AWS. However, I'd be happy to hear about your experience and the way you have solved it (since it might help other devs one day). Please, keep me updated.

**Comment by Miserlou** [comment]
Okay. Thanks for your prompt reply. On Monday I'll pull this thread: https://github.com/sabricot/django-elasticsearch-dsl/issues/40#issuecomment-322044723

It'd be best if I could just a) not send this header/send custom headers b) pass an ES JSON response directly into es-dsl rather than it having it call the endpoint itsellf.

**Comment by barseghyanartur** [comment]
@Miserlou:

Answering to your question, I rely on ``elasticsearch-dsl``, which itself operates with Elastic (sends headers). I see you can do that in [elasticsearch-py](https://elasticsearch-py.readthedocs.io/en/master/connection.html#transport). I'm not sure where to do that in ``elasticsearch-dsl-py``. If you find that out and there's a need to make it customisable (most likely, on the viewset level), I'll make appropriate additions.

Please, do some research and let me know.

**Comment by Miserlou** [comment]
This ended up being an AWS permissions error. Adding `es:<my service>` to the EC2 user fixed this. Not sure what was happening under the hood but it worked.

**Comment by barseghyanartur** [comment]
I'm closing this. However, it would be great to hear in details how you solved the Amazon issue, since it might be useful to other folks. Please, consider writing an article about it. I'd like to put it in the [wiki](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/wiki).
