### ISSUE TITLE
[Question] How To Implement Partial/Fuzzy Search

### ISSUE THREAD

**Issue by Miserlou** [barseghyanartur/django-elasticsearch-dsl-drf#110]
So, I've got everything working nicely now (so fast and easy, wow!)

However, it seems like the search is very strict. For instance, a user must supply "medulloblastoma" to get any results, not just "medullo" or "blastoma".

What's the best way to solve this? I've thought that I could either change the tokenizer from keyword to something with ngrams, or I can add wildcard search results, but I don't see any documentation here on how to do either of that, or what the best approach would be.

Do you have any suggestions?
Thanks!
Rich

**Comment by Miserlou** [comment]
Perhaps fuzzy isn't the right word here, just partials would be fine.

**Comment by barseghyanartur** [comment]
@Miserlou:

Use ngrams. 

- Partially shown [here](https://django-elasticsearch-dsl-drf.readthedocs.io/en/0.17.2/advanced_usage_examples.html?highlight=ngram#id8). 
- [The basic idea](https://www.elastic.co/guide/en/elasticsearch/guide/current/_ngrams_for_partial_matching.html).

**Comment by Miserlou** [comment]
Great! Thanks!
