### ISSUE TITLE
jwt_auth

### ISSUE THREAD

**Issue by jacque99** [barseghyanartur/django-elasticsearch-dsl-drf#113]
@barseghyanartur 
I would like to use jwt auth.
Please tell me what to put in settings.ELASTICSEARCH_DSL?

My authentication server responds to below request correctly:
curl "http://localhost:8000/api/user/" -H "Authorization: JWT header.payload.signature"

My readonlyrest.yml includes below:
jwt:
- name: jwt_provider_1
signature_algo: HMAC
signature_key: "your_signature_min_256_chars"
user_claim: username
roles_claim: resource_access.client-app.roles # JSON-path style
header_name: Authorization

**Comment by barseghyanartur** [comment]
@jacque99:

That's some sort of off-topic and not anyhow related to this library. Google/Bing is your friend. Search for how to use JWT with Django REST Framework. [Good article about it](https://simpleisbetterthancomplex.com/tutorial/2018/12/19/how-to-use-jwt-authentication-with-django-rest-framework.html).
