### ISSUE TITLE
get_object method ignores the check_object_permissions call

### ISSUE THREAD

**Issue by piedrahitapablo** [barseghyanartur/django-elasticsearch-dsl-drf#116]
Currently the `get_object` method of the `BaseDocumentViewSet ` class ignores the call to `self.check_object_permissions` (https://www.django-rest-framework.org/api-guide/generic-views/#get_objectself). Is there any reason for ignoring this call? or could it be implemented having in mind that the permission classes used for a `DocumentViewSet` need to implement the `has_object_permission` method taking into account that the `obj` argument will not be an instance of a django model?

Thanks for developing this library, it has been very useful on the projects that I'm currently working.

**Comment by barseghyanartur** [comment]
@piedrahitapablo:

Please, check the latest master. If it works for you, I'll prepare a release.

**Comment by piedrahitapablo** [comment]
Yes it works, thank you!

**Comment by barseghyanartur** [comment]
@piedrahitapablo:

Released in 0.17.3.
