### ISSUE TITLE
Serializing empty values

### ISSUE THREAD

**Issue by FalFire** [barseghyanartur/django-elasticsearch-dsl-drf#118]
I am trying to serialize instances of a DocType subclass which has fields that can be None. These are removed from the Hit object by elasticsearch-py-dsl and therefore cause errors when serialized by subclasses of DocumentSerializer ('Hit' object has no attribute 'x'). What is the correct way to define serializers/DocType subclasses as to support None/empty values on documents which you still want to serialize in your API (as null)?

Using any combination of blank=True, null=True and default=x does not work.

**Comment by barseghyanartur** [comment]
@FalFire:

Please, check the example project (clone, checkout, install reqs, build index, run the dev server). You will find it working there. Follow the examples and documentation guidelines.

**Comment by FalFire** [comment]
From experimenting some more my conclusion is that the only way to support empty values like None in serializer output is to redefine all fields which can be None on the serializer itself and add the parameters required=False, default=...? Is there any way to declare this on documents (subclasses of DocType)?

**Comment by barseghyanartur** [comment]
@FalFire:

Serializers are based on your document definition. Honestly, I can't reproduce your issue.

- What version of Elasticsearch are you using?
- What are your `elasticsearch` and `elasticsearch-dsl` versions?
- What's your Python version?
- What your Django version?
- Take a look at [the Book model](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/examples/simple/books/models/book.py#L19). The `summary` field can be None. Works with [BookDocumentSimpleSerializer serializer, which only lists the fields it should have](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/examples/simple/search_indexes/serializers/book.py#L85), check the [document definition](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/examples/simple/search_indexes/documents/book.py#L88).

I've just set all the summary fields of my Book model to None, then synced Elastic indexes. This is the output.

![desdd Screenshot from 2019-03-13 12-15-01](https://user-images.githubusercontent.com/4925587/54275036-e9642000-4589-11e9-8149-80b411ce8bce.png)
