### ISSUE TITLE
Fix SearchFilterBackend get_schema_fields

### ISSUE THREAD

**Issue by chen2aaron** [barseghyanartur/django-elasticsearch-dsl-drf#119]
https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/c8cc7fb5cb07f10c9983f6c664367e2519eef1d8/src/django_elasticsearch_dsl_drf/filter_backends/search/historical.py#L257

It should be ```name=self.search_param,```

**Comment by barseghyanartur** [comment]
@chen2aaron:

Thanks. It will be released with the next release.
