### ISSUE TITLE
Is it possible to search sub string in word ?

### ISSUE THREAD

**Issue by kdbusiness90** [barseghyanartur/django-elasticsearch-dsl-drf#125]
Hello,

I want to search "goo" in the below words.

- google
- goodwill.
- goodness.
- mongoose.
- goofball.
- goodwife.
- goodlier.
- dragoons.
- goodbyes.

Is it possible in using any search query ? Sorry i new to elasticsearch.

**Comment by barseghyanartur** [comment]
https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/docs/faq.rst
