### ISSUE TITLE
Can we use Django restframework serializers.ModelSerializer directly ?

### ISSUE THREAD

**Issue by kdbusiness90** [barseghyanartur/django-elasticsearch-dsl-drf#126]
Hello,

In my Model(called Note), I have around 100 fields but I want to index on few fields (e.g just 3 fields). 

If I defined all 100 fields in class Document(DocType), it will do the indexing on all fields, right? which is not need.

Currently, I have created the below Document which contains just 3 fields.

    user_id = fields.IntegerField()

    description = fields.StringField(
        fields={
            'raw': fields.StringField(analyzer='keyword', fielddata=True),
        }
    )

    subject = fields.StringField(
        analyzer=html_strip,
        fields={
            'raw': fields.StringField(analyzer='keyword', fielddata=True),
        }
    )

 But in thiscase i am serializing only 3 fields and i required all 100 fields to be serialized .

Please let me know how to serialize all 100 fields without indexing in class Document(DocType).

**Comment by barseghyanartur** [comment]
Please, rewrite your question in a better English. I don't understand you clearly.

**Comment by barseghyanartur** [comment]
https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/docs/faq.rst

**Comment by kdbusiness90** [comment]
@barseghyanartur, you mentioned, we can use `serializers.ModelSerializer` Class but [here](https://django-elasticsearch-dsl-drf.readthedocs.io/en/latest/quick_start.html?highlight=serializer#serializer-definition) i can the examples of  `DocumentSerializer` and `serializers.Serializer`.

Please confirm, can we use `serializers.ModelSerializer` Class ?

Apology for the inconvenience.

**Comment by barseghyanartur** [comment]
No. But you can define fields yourself.

**Comment by kdbusiness90** [comment]
Thanks for quick reply!!

**Comment by barseghyanartur** [comment]
@kdbusiness90:

I think you got it all so wrong. All your assumptions, your uses cases - they all so very wrong.

- Your Model may have 1000 fields.
- You don't have to have them all indexed. In your Document you could have just 3 fields.
- In your DocumentSerializer you only mention these 3 fields. You don't even have to declare them explicitly. Dynamic serializer would do it for you.

You missing some ground understanding here. I could consult you further, but it won't be for free. If you're interested, contact me for the details.

**Comment by kdbusiness90** [comment]
> * Your Model may have 1000 fields.
> * You don't have to have them all indexed. In your Document you could have just 3 fields.
> * In your DocumentSerializer you only mention those 3 fields. You don't even have to declare them explicitly. Dynamic serializer would do it for you.

I followed doc and your instructions but I am getting the error below error:

```
ges/django_elasticsearch_dsl_drf/helpers.py", line 81, in <genexpr>
    (key, unsorted_dict[key]) for key in __sorted_keys
KeyError: 'public'
```

Where **public** is a field, defined in models.py.

**NoteDocument**

```
@INDEX.doc_type
class NoteDocument(DocType):
    """
    NoteIndexing
    """
    id = fields.IntegerField(attr='id')

    user_id = fields.IntegerField()

    description = fields.StringField(
        fields={
            'raw': fields.KeywordField(),
            'suggest': fields.CompletionField(),
            'edge_ngram_completion': fields.StringField(
                analyzer=edge_ngram_completion
            ),
        }
    )

    modified_at = fields.DateField()

    subject = fields.StringField(
        analyzer=html_strip,
        fields={
            'raw': fields.StringField(index=False),
        }
    )

    title_filing = fields.StringField(
        analyzer=html_strip,
        fields={
            'raw': fields.StringField(analyzer='keyword', fielddata=True),
        }
    )

    class Meta(object):
        """Meta options."""

        model = Notes
```

**DocumentSerializer**

```
class ElasticNotesSerializer(DocumentSerializer):

    class Meta:
        document = NoteDocument
        fields = ('id', 'user_id', 'title_filing', 'description', 'subject', 'modified_at', 'public')
```

**Comment by kdbusiness90** [comment]
> * Your Model may have 1000 fields.
> * You don't have to have them all indexed. In your Document you could have just 3 fields.
> * In your DocumentSerializer you only mention those 3 fields. You don't even have to declare them explicitly. Dynamic serializer would do it for you.

I followed doc and your instructions but I am getting the error below error:

```
ges/django_elasticsearch_dsl_drf/helpers.py", line 81, in <genexpr>
    (key, unsorted_dict[key]) for key in __sorted_keys
KeyError: 'public'
```

Where **public** is a field, defined in models.py.

**NoteDocument**

```
@INDEX.doc_type
class NoteDocument(DocType):
    """
    NoteIndexing
    """
    id = fields.IntegerField(attr='id')

    user_id = fields.IntegerField()

    description = fields.StringField(
        fields={
            'raw': fields.KeywordField(),
            'suggest': fields.CompletionField(),
            'edge_ngram_completion': fields.StringField(
                analyzer=edge_ngram_completion
            ),
        }
    )

    modified_at = fields.DateField()

    subject = fields.StringField(
        analyzer=html_strip,
        fields={
            'raw': fields.StringField(index=False),
        }
    )

    title_filing = fields.StringField(
        analyzer=html_strip,
        fields={
            'raw': fields.StringField(analyzer='keyword', fielddata=True),
        }
    )

    class Meta(object):
        """Meta options."""

        model = Notes
```

**DocumentSerializer**

```
class ElasticNotesSerializer(DocumentSerializer):

    class Meta:
        document = NoteDocument
        fields = ('id', 'user_id', 'title_filing', 'description', 'subject', 'modified_at', 'public')
```

**Comment by kdbusiness90** [comment]
> * Your Model may have 1000 fields.
> * You don't have to have them all indexed. In your Document you could have just 3 fields.
> * In your DocumentSerializer you only mention those 3 fields. You don't even have to declare them explicitly. Dynamic serializer would do it for you.

I followed doc and your instructions but I am getting the error below error:

```
ges/django_elasticsearch_dsl_drf/helpers.py", line 81, in <genexpr>
    (key, unsorted_dict[key]) for key in __sorted_keys
KeyError: 'public'
```

Where **public** is a field, defined in models.py.

**NoteDocument**

```
@INDEX.doc_type
class NoteDocument(DocType):
    """
    NoteIndexing
    """
    id = fields.IntegerField(attr='id')

    user_id = fields.IntegerField()

    description = fields.StringField(
        fields={
            'raw': fields.KeywordField(),
            'suggest': fields.CompletionField(),
            'edge_ngram_completion': fields.StringField(
                analyzer=edge_ngram_completion
            ),
        }
    )

    modified_at = fields.DateField()

    subject = fields.StringField(
        analyzer=html_strip,
        fields={
            'raw': fields.StringField(index=False),
        }
    )

    title_filing = fields.StringField(
        analyzer=html_strip,
        fields={
            'raw': fields.StringField(analyzer='keyword', fielddata=True),
        }
    )

    class Meta(object):
        """Meta options."""

        model = Notes
```

**DocumentSerializer**

```
class ElasticNotesSerializer(DocumentSerializer):

    class Meta:
        document = NoteDocument
        fields = ('id', 'user_id', 'title_filing', 'description', 'subject', 'modified_at', 'public')
```

**Comment by kdbusiness90** [comment]
> * Your Model may have 1000 fields.
> * You don't have to have them all indexed. In your Document, you could have just 3 fields.
> * In your DocumentSerializer you only mention those 3 fields. You don't even have to declare them explicitly. Dynamic serializer would do it for you.

I followed doc and your instructions but I am getting the error below error:

```
ges/django_elasticsearch_dsl_drf/helpers.py", line 81, in <genexpr>
    (key, unsorted_dict[key]) for key in __sorted_keys
KeyError: 'public'
```

Where **public** is a field, defined in models.py.

**NoteDocument**

```
@INDEX.doc_type
class NoteDocument(DocType):
    """
    NoteIndexing
    """
    id = fields.IntegerField(attr='id')

    user_id = fields.IntegerField()

    description = fields.StringField(
        fields={
            'raw': fields.KeywordField(),
            'suggest': fields.CompletionField(),
            'edge_ngram_completion': fields.StringField(
                analyzer=edge_ngram_completion
            ),
        }
    )

    modified_at = fields.DateField()

    subject = fields.StringField(
        analyzer=html_strip,
        fields={
            'raw': fields.StringField(index=False),
        }
    )

    title_filing = fields.StringField(
        analyzer=html_strip,
        fields={
            'raw': fields.StringField(analyzer='keyword', fielddata=True),
        }
    )

    class Meta(object):
        """Meta options."""

        model = Notes
```

**DocumentSerializer**

```
class ElasticNotesSerializer(DocumentSerializer):

    class Meta:
        document = NoteDocument
        fields = ('id', 'user_id', 'title_filing', 'description', 'subject', 'modified_at', 'public')
```

**Comment by kdbusiness90** [comment]
@barseghyanartur, please share your contact details.

**Comment by barseghyanartur** [comment]
@kdbusiness90:

It's mentioned in the [README.rst](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf#author).
