### ISSUE TITLE
GenericDocumentViewSet class

### ISSUE THREAD

**Issue by ar7n** [barseghyanartur/django-elasticsearch-dsl-drf#127]
Hello. There is no way to create viewset with only list/retrieve/suggest method with current DocumentViewSet classes. May be there is a point to create GenericDocumentViewSet class inheriting drf GenericViewSet class and move get_object and get_queryset methods there? I can make PR.

**Comment by barseghyanartur** [comment]
@ar7n:

1. Describe your problem. Explain WHAT do you want to achieve, instead of HOW do you want to achieve it.

2. There is a [BaseDocumentViewSet](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/src/django_elasticsearch_dsl_drf/viewsets.py#L146) class.

**Comment by ar7n** [comment]
@barseghyanartur I want to create viewset with suggest action, but i don't need list and retireve actcions for this viewset/model.

**Comment by barseghyanartur** [comment]
@ar7n:

I see. Please, make a pull request if you have time.
