### ISSUE TITLE
Changing queryset resolves a orderring error

### ISSUE THREAD

**Issue by 0xHM** [barseghyanartur/django-elasticsearch-dsl-drf#129]
Once I change value of queryset on BaseDocumentViewSet,  I get following error :

`  File "~/.env/lib/python2.7/site-packages/django_elasticsearch_dsl_drf/filter_backends/ordering/common.py", line 314, in filter_queryset
    return queryset.sort(*ordering_query_params)
AttributeError: 'QuerySet' object has no attribute 'sort'
`

What Im trying to do is following : 

Change the queryset of BaseDocumentViewSet, to 

```

class PartnerDocumentView(BaseDocumentViewSet):
    """The PublisherDocument view."""
    document = PartnerDocument
    serializer_class = PartnerDocumentSerializer

    lookup_field = 'id'
    paginate_by = 5

    filter_backends = [
        FilteringFilterBackend,
        OrderingFilterBackend,
        CompoundSearchFilterBackend,
        DefaultOrderingFilterBackend,
    ]
    # Define search fields
    search_fields = (
        'name',
        'address',
        'city',

    )
    # Define filtering fields
    filter_fields = {
        'id': None,
        'name': 'name.raw',
        'city': 'city.raw',
    }
    # Define ordering fields
    ordering_fields = {
        'id': None,
        'name': None,
        'city': None,
    }
    # Specify default ordering
    ordering = ('id', 'name',)

    def get_queryset(self):
        company = Company.objects.get(id=self.kwargs['company_id'])
        records = company.partner_set.all()
        return records

```

Any ideas why is this happening ?

**Comment by ar7n** [comment]
@0xHM you should use elasticsearch-dsl Search objects instead of django QuerySet in BaseDocumentViewSet

**Comment by barseghyanartur** [comment]
@0xHM:

See the remark of @ar7n.

In this case you deal with `PartnerDocument` queries (Elasticsearch) and not with `Partner` (Django model). If you want to filter on `company_id` you will need to make sure it's properly indexed. However, your approach looks rather strange. You could as well pass `company_id` as a GET param and enable `company_id` as a filter on the `PartnerDocumentView`. I advise you to take a deeper look into documentation.
