### ISSUE TITLE
read_only_allow_delete is ignored

### ISSUE THREAD

**Issue by robben1234** [barseghyanartur/django-elasticsearch-dsl-drf#134]
**Describe the bug**
I keep getting `[FORBIDDEN/12/index read-only / allow delete (api)];` error when saving indeced models despite having `blocks={'read_only_allow_delete': None},` in settings

**To Reproduce**
1. Create an Index with settings `search_index.settings(
    number_of_shards=1,
    number_of_replicas=0,
    blocks={'read_only_allow_delete': None},
)`
2. Save linked model instance
3. See error

**Expected behavior**
Save model without errors

**Additional context**
I was able to save model once, after applying this setting directly via curl (`curl -XPUT -H "Content-Type: application/json" http://localhost:9200/_all/_settings -d '{"index.blocks.read_only_allow_delete": null}'
`) to _all. But then for the next request it returned error again.

**Comment by barseghyanartur** [comment]
@robben1234:

I'm not sure why. The way done [here](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/examples/simple/search_indexes/documents/book.py#L18) works for me.

I would go raise an issue at [django-elasticsearch-dsl](https://github.com/sabricot/django-elasticsearch-dsl), since that's who's responsible for the sync.

**Comment by barseghyanartur** [comment]
@robben1234:

Hey, just remembered that I got that issue once as well and back then it was related to low storage (less than 4 GB of space left). You might want to check that.

https://discuss.elastic.co/t/forbidden-12-index-read-only-allow-delete-api/110282

**Comment by robben1234** [comment]
Thanks. I didn't bring this issue to django-elasticsearch-dsl because I eventually found out that local machine has less than 10 gb of storage (which is default [flood stage](https://www.elastic.co/guide/en/elasticsearch/reference/current/disk-allocator.html) mark) and changed config to not trigger readonly mode in this case. This [stackoverflow question](https://stackoverflow.com/questions/50609417/elasticsearch-error-cluster-block-exception-forbidden-12-index-read-only-all) is relevant.

```
PUT _cluster/settings
{
  "transient": {
    "cluster.routing.allocation.disk.watermark.low": "9gb",
    "cluster.routing.allocation.disk.watermark.high": "5gb",
    "cluster.routing.allocation.disk.watermark.flood_stage": "1gb",
    "cluster.info.update.interval": "1m"
  }
}
```
