### ISSUE TITLE
Is it possible to use paginate queryset directly in a view function

### ISSUE THREAD

**Issue by mathewtrivett** [barseghyanartur/django-elasticsearch-dsl-drf#135]
Firstly thanks for building this great package. I'm working on an API but implementing a custom `list` function.

In I need to fetch paginated results from elastic search but then look up the results data from a cache.

My current function looks a bit like this:

```
def list(self, request):
        queryset = self.filter_queryset(self.get_queryset())
        cached_data = []
        for hit in queryset.execute():
            data = cache.get(hit.id)
            if data == None:
                instance = Model.objects.get(pk=hit.id)
                data = update_cache(Model, instance=instance)
            cached_data.append(data)
        return self.get_paginated_response(cached_data)
```

I am currently getting the error `'PageNumberPagination' object has no attribute 'page'` and when I try including this:

`page = self.paginate_queryset(queryset)`

`paginate_queryset` returns None

**Comment by barseghyanartur** [comment]
@mathewtrivett:

I'm not sure why are you getting that error. The devil is in details.

However, I'm curious of what are you trying to achieve by that? Speed-ups? It might very well be that you're trying to do it the wrong way.

**Comment by mathewtrivett** [comment]
I'm using an API that doesn't allow me to permanently store their data. So I've implemented a system where basic data is stored in my database and elasticsearch. Then when I get search results in a query I hit their API and cache the data for a few days. Subsequent hits from an elastic search query then read from the cache.

There might be a more elegant way to achieve something similar but it's what I have right now.

Is there any thoughts on why the Paginator is returning None? What would be the typical lifecycle if you wanted to paginate a queryset?

**Comment by barseghyanartur** [comment]
@mathewtrivett:

I see. So, the basic information you already have, right? That's what you should paginate on. However, as far I understand, you are fetching some additional data from your cache, which you empty periodically.

The Django REST Framework serializers have flexible data properties. So, I would simply delegate that to the serializer. See the [following example](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/examples/simple/search_indexes/serializers/publisher.py#L56).

Note the ``get_location`` method and the ``location`` ``SerializerMethodField`` definition. Thus, in the body of the ``get_location`` method I would query the cache and return cache results for that speciic record (it shall be JSON serializable).

I hope that helps.

**Comment by barseghyanartur** [comment]
@mathewtrivett:

In addition to my answer (above), if you do it the way I propose, you wouldn't need to alter the pagination behaviour.

**Comment by mathewtrivett** [comment]
Thanks that’s really helpful. For now I’ve created a serialiser for the Document and removed the custom list but I just get back a list of JSON objects 10 long with no pagination. Calling ?page=2 has no effect despite there being +200k documents in the index?

**Comment by barseghyanartur** [comment]
@mathewtrivett:

Did you properly configure pagination settings of Django REST Framework? See [this](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/examples/simple/settings/base.py#L255) as an example.

**Comment by mathewtrivett** [comment]
@barseghyanartur That worked great! I just want to say thanks so much for being helpful and troubleshooting with me. I'll close this now and shift my caching logic to serialisers.

Thanks for your work on this.

**Comment by barseghyanartur** [comment]
@mathewtrivett:

You're welcome. One last thing. Performance wise, I wouldn't directly do the cache updates in the serializer, but rather spawn it as a celery task.
