### ISSUE TITLE
MonkeyCoded to make it run but anyway love it

### ISSUE THREAD

**Issue by DmitryMake** [barseghyanartur/django-elasticsearch-dsl-drf#140]
Hello! Thank you for this awesome package. I love it so much.
Anyway I got into troubles truying to make it run. I think it's all my fault, so I will be happy if you correct my mistakes.

First of all I installed:
```
elasticsearch-dsl==6.4.0
django-elasticsearch-dsl-drf==0.18
```
And pulled elasticsearch docker image 6.4.1 as in example.

Added it to settings and made it work, created Document, but got an error:
`AttributeError: type object 'MyDocument' has no attribute 'Django'`
[Here](https://github.com/sabricot/django-elasticsearch-dsl) found that it supposed to me a Django class, not Meta.

So I corrected this:
```
class MyDocument(DocType):
    ...
    class Django:
    model = My
```
After that I got an error:
`'DocumentOptions' object has no attribute 'using'`
I discovered it was because of `self.document._doc_type.using ` line in `DocumentViewSet.__init__`, so I replaced it with `self.document._get_using()`.
After that I got 3 or 4 more mistakes, so I made this:

```
# this is used to raplace DocumentViewSet.__init__ method
def patched_constructor(self, *args, **kwargs):
    assert self.document is not None
    # patched from here
    self.client = connections.get_connection(
            self.document._get_using()
            )
    self.index = self.document._index
    self.mapping = self.document._doc_type.mapping.properties.name
    self.search = Search(
            using=self.client,
            index=self.index._name,
            doc_type=self.document._doc_type.name
    )
    # to here

# this is used to replace DocumentViewSet.get_queryset method
def patched_get_queryset(self):
    queryset = self.search.query()
    # patched from here
    queryset.model = self.document.django.model
    # to here
    return queryset

# this is used to replace DocumentSerializer.get_fields method
def patched_get_fileds(self):
    __fields = self.Meta.fields
    exclude = self.Meta.exclude
    ignore_fields = self.Meta.ignore_fields
    document = self.Meta.document
    # patched from here
    model = document.django.model
    document_fields = document._fields
    # to here
    declared_fields = copy.deepcopy(self._declared_fields)
    field_mapping = OrderedDict()

    for field_name, field_type in six.iteritems(document_fields):
        orig_name = field_name[:]

        if orig_name in ignore_fields or field_name in ignore_fields:
            continue
        if exclude:
            if orig_name in exclude or field_name in exclude:
                continue
            if __fields:
                if orig_name not in __fields and field_name not in __fields:
                    continue

        kwargs = self._get_default_field_kwargs(
            model,
            field_name,
            field_type
        )
        if field_type.__class__ not in self._field_mapping:
            continue

        field_mapping[field_name] = \
            self._field_mapping[field_type.__class__](**kwargs)

    if declared_fields:
        for field_name in declared_fields:
            field_mapping[field_name] = declared_fields[field_name]

    field_mapping = sort_by_list(field_mapping, __fields)
    return field_mapping

```
It looks like everithing is connected with that `class Django` used in my document. Is it a simple way to avoid mistakes? Anyway  it is a great package, you make using ElasticSearch much easier.
Thanks!

**Comment by CorrosiveKid** [comment]
I'm running into the same issue. I think this was because of some changes in the new version of django-elasticsearch-dsl which was released recently.

**Comment by jamilnoyda** [comment]
I'm having the same issue

**Comment by CorrosiveKid** [comment]
> I'm having the same issue

@jamilnoyda You should be able to install from source and get around this issue. Master contains changes to get this working with django-elasticsearch-dsl > 6.4.

**Comment by barseghyanartur** [comment]
Version 0.19 (released on PyPI) contains the changes.
