### ISSUE TITLE
Installation fails due to conflicting elasticsearch-dsl version

### ISSUE THREAD

**Issue by NeolithEra** [barseghyanartur/django-elasticsearch-dsl-drf#146]
Hi, users are unable to run **_django-elasticsearch-dsl-drf_** due to dependency conflict with _**elasticsearch-dsl**_ package. 
As shown in the following full dependency graph of **_django-elasticsearch-dsl-drf_**, **_django-elasticsearch-dsl-drf_** requires _**elasticsearch-dsl**_，while **_django-elasticsearch-dsl>=0.3_** equires _**elasticsearch-dsl>=6.4.0,<7.0.0**_.

According to pip’s “first found wins” installation strategy, _**elasticsearch-dsl 7.0.0 (the latest version)**_ is the actually installed version. 
However, _**elasticsearch-dsl 7.0.0**_ does not satisfy _**elasticsearch-dsl>=6.4.0,<7.0.0**_.

### Dependency tree-----
```
django-elasticsearch-dsl-drf(version range:)
| +-six(version range:>=1.9)
| +-django-nine(version range:>=0.1.10)
| +-django-elasticsearch-dsl(version range:>=0.3)
| | +-elasticsearch-dsl(version range:>=6.4.0,<7.0.0)
| +-elasticsearch-dsl(version range:)
| +-elasticsearch(version range:)
| +-djangorestframework(version range:)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution

1.	Fix your direct dependency to be **_elasticsearch-dsl>=6.4.0,<7.0.0_**. I have checked this revision will not affect your downstream projects now.
2.	Ask your upstream project **_django-elasticsearch-dsl_** to loose the version range of **_elasticsearch-dsl>=6.4.0_**.
Which solution do you prefer, 1 or 2?

Please let me know your choice. I can submit a PR to solve this issue.

**Comment by barseghyanartur** [comment]
I'll check things with pip-tools soon and likely include requirements for all major versions. Thanks!

**Comment by barseghyanartur** [comment]
At the moment of writing, this library works with all supported versions of Elasticsearch and ``django-elasticsearch-dsl``. See the [travis](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/.travis.yml) and [tox](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/tox.ini).
