### ISSUE TITLE
Implement AND and OR lookups

### ISSUE THREAD

**Issue by Antman261** [barseghyanartur/django-elasticsearch-dsl-drf#15]
Similar to Django-filter's MultipleChoiceFilter providing a `conjoined=True` property.
Reference https://django-filter.readthedocs.io/en/master/ref/filters.html#multiplechoicefilter

I need compatibility with django rest framework query-string behaviour, which allows me to do `?field=value&field=value2` and have it return only results where field has both `value` AND `value2`.

**Comment by barseghyanartur** [comment]
@Antman261:

See [Filtering](http://django-elasticsearch-dsl-drf.readthedocs.io/en/0.5.1/advanced_usage_examples.html#filtering) - **Filter documents by multiple fields** section.

This is OR:

```text
/search/books/?tags__in=education|economy
```

This is OR too:

```text
/search/books/?tags=education&tags=economy
```

This is AND:

```text
/search/books/?tags__term=education&tags__term=economy
```

If that doesn't completely solve your issue, let me know.

**Comment by Antman261** [comment]
I just tried it and the results don't change even without the filters. In short, they're not doing anything. 

Here's my document and viewset.
```python
class RecipeDocument(DocType, BaseDocumentMixin):
    pg_id = fields.IntegerField(attr='id')
    name = fields.TextField()
    description = fields.TextField()
    keywords = fields.ListField(fields.KeywordField())
    ...
```
My viewset looks like this
```python
class RecipeDocumentViewSet(BaseDocumentViewSet):
    document = RecipeDocument
    permission_classes = [IsAuthenticatedOrReadOnly]
    serializer_class = RecipeDocumentSerializer
    lookup_field = 'pg_id'
    filter_backends = [
        FilteringFilterBackend,
        IdsFilterBackend,
        OrderingFilterBackend,
        DefaultOrderingFilterBackend,
        FoodRankRecipeFilterBackend,
        # SearchFilterBackend,
    ]
    search_fields = ('name', 'description', 'ingredients', 'keywords')
    filter_fields = {
        'keywords': {
            'field': 'keywords',
            'lookups': [
                LOOKUP_FILTER_TERMS,
                LOOKUP_FILTER_WILDCARD
            ]
        },
    ...
```

**Comment by barseghyanartur** [comment]
This I don't understand:

> I just tried it and the results don't change even without the filters. In short, they're not doing anything.

Could you provide more information (model, sample data that you're testing with, versions)? And a request example?
A correspondent raw Elastic query (from ``Django Debug Toolbar``) would be useful as well.

**Comment by Antman261** [comment]
I just got it working with `keywords__terms=` rather than `keywords__term=`
Seems the docs don't match the API?

The full story here is that I'm trying to achieve parity with an existing Postgresql api that uses FilterSets, so that I can switch over.

**Comment by barseghyanartur** [comment]
Related to [issue 20](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/issues/20). Once that's done, this can be closed.

**Comment by barseghyanartur** [comment]
Since initial ``simple_query_string`` is implemented (in a dedicated branch - to be soon released), I'm closing this issue. See my comment above (issue #20) for a reference.

**Comment by andrijan** [comment]
Hey @barseghyanartur 

Is it possible to `OR` together 2 different filter types?

What I mean is I would like this to be `OR` (I want all posts that have a deadline greater than now or post that don't have a deadline)

`/search/post/?deadline__gt=now&deadline__isnull=true`

**Comment by barseghyanartur** [comment]
@andrijan:

Not at the moment with `FilteringFilterBackend`, but you can make your own (inherit from that one) and override `apply_query` and `apply_filter` methods.
