### ISSUE TITLE
Issue when trying to use a custom lookup field other than `id` with Elasticsearch 7.x

### ISSUE THREAD

**Issue by CorrosiveKid** [barseghyanartur/django-elasticsearch-dsl-drf#150]
**Describe the bug**
```AttributeError: 'AttrDict' object has no attribute 'get'``` when using a custom lookup field other than `id` with Elasticsearch 7.x

**To Reproduce**
1. Setup a viewset based off `from django_elasticsearch_dsl_drf.viewsets import BaseDocumentViewSet` with a `lookup_field` other than `id`. (eg. `lookup_field = 'isbn'` using the books example.
2. Try using the detail endpoint for the above viewset.
3. You would get the error ```AttributeError: 'AttrDict' object has no attribute 'get'```

**Expected behavior**
The detail endpoint should work with the custom lookup field.

**Comment by barseghyanartur** [comment]
@CorrosiveKid:

Great, thanks. Could you also make an additional test case for it (just to make sure it doesn't break in future).

**Comment by CorrosiveKid** [comment]
Will do.

**Comment by barseghyanartur** [comment]
Thanks! Btw, yesterday released as hotfix in 0.20.1.

**Comment by CorrosiveKid** [comment]
Yeah I noticed, thanks for that!
