### ISSUE TITLE
Add test case to test the scenario of a custom lookup field

### ISSUE THREAD

**Issue by CorrosiveKid** [barseghyanartur/django-elasticsearch-dsl-drf#152]
Some document viewsets can use a custom lookup field rather than the default id lookup. It's good to have test coverage around this feature.

Related issue: #150 

https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/issues/150#issuecomment-522269838

**Comment by barseghyanartur** [comment]
Released in 0.20.2.
