### ISSUE TITLE
PageNumberPagination get_count method does not provide override

### ISSUE THREAD

**Issue by helrond** [barseghyanartur/django-elasticsearch-dsl-drf#154]
**Describe the bug**
When using django_elasticsearch_dsl_drf.pagination.PageNumberPagination I am getting an `Object of type 'AttrDict' is not JSON serializable` error. The `get_count` method on this class appears to handle this logic, but it does not appear to be called. This may be related to Django Rest Framework version.

**To Reproduce**
Create a standard view which uses the PageNumberPagination class (see dependency versions below). DRF's PageNumberPagination works as expected.

**Expected behavior**
I expect the page to render as usual.

**Proposed fix**
- Change the [count definition](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/src/django_elasticsearch_dsl_drf/pagination.py#L183) to `self.page.paginator.count` (which is what [DRF uses](https://github.com/encode/django-rest-framework/blob/master/rest_framework/pagination.py#L219))
- Alternatively, call `get_count()` explicitly, which may have better backwards compatibility.

**Additional context**
Elasticsearch v7.0.0
`Django==2.0.13`
`django-elasticsearch-dsl==7.0.0`
`django-elasticsearch-dsl-drf==0.19`
`djangorestframework==3.10.2`

**Comment by barseghyanartur** [comment]
@helrond:

Thanks for reporting this. I haven't tested it with DRF 3.10.x yet. The rest of the reqs looks OK. Could you confirm that it works for you in 3.9.x?

**Comment by helrond** [comment]
Hmmm I am still experiencing this with DRF 3.9.x, so it must be something about how my views are set up. I'm trying to dig through the various overrides to see where I'm missing something.

**Comment by barseghyanartur** [comment]
@helrond:

Ah, I see. The thing is that you're using ``Elasticsearch`` 7.x. Support for 7.x was added in ``django-elasticsearch-dsl-drf`` 0.20, with some minor fixes in 0.20.1. I suggest you upgrade and test again.

**Comment by barseghyanartur** [comment]
@helrond:

Additionally, see the [CHANGELOG.rst](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/CHANGELOG.rst).

**Comment by helrond** [comment]
Thanks @barseghyanartur - confirming that updating to `0.20.1` resolved this issue for me.
