### ISSUE TITLE
Search any word in indexed fields

### ISSUE THREAD

**Issue by MiltosD** [barseghyanartur/django-elasticsearch-dsl-drf#156]
I would like to know how I should define my fields in order to achieve a search where the words of the given query are in the indexed fields. 

For example, I have a `description` field where indexed value is "**This is a short indexed description**". When I do _/?search=**short indexed description**_, I get the document but this does not happen when I do _/?search=**a description**_ or  _/?search=**short description**_. 

I have defined the field as

`
description = fields.StringField(
        analyzer=html_strip,
        fields={
            'raw': fields.StringField(
                analyzer='keyword'
            )
        }
    )
`
I would appreciate your help

**Comment by barseghyanartur** [comment]
@MiltosD:

Which search backend are you using?

**Comment by MiltosD** [comment]
@barseghyanartur 

In my viewset, extending BaseDocumentViewSet:

`
filter_backends = [
        FilteringFilterBackend,
        OrderingFilterBackend,
        DefaultOrderingFilterBackend,
        FacetedSearchFilterBackend,
        CompoundSearchFilterBackend,
        MatchPhraseFilterBackend
    ]
`

**Comment by MiltosD** [comment]
> @barseghyanartur
> 
> In my viewset, extending BaseDocumentViewSet:
> 
> `filter_backends = [ FilteringFilterBackend, OrderingFilterBackend, DefaultOrderingFilterBackend, FacetedSearchFilterBackend, CompoundSearchFilterBackend, MatchPhraseFilterBackend ]`

Would it work if I added MultiMatchQueryBackend? Didn

**Comment by barseghyanartur** [comment]
@MiltosD:

I can't reproduce it. See the [tests that I wrote to cover your issue](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/src/django_elasticsearch_dsl_drf/tests/test_search.py#L393) and check your code.
