### ISSUE TITLE
Bucket list size

### ISSUE THREAD

**Issue by MiltosD** [barseghyanartur/django-elasticsearch-dsl-drf#159]
Hello, 

I've been looking in the documentation how to increase the bucket list size which seems to be always 10. This is because I have 60 documents with a language field, different to each one, but only the first 10 appear in the facets result. Is there any configuration for that?

**Comment by barseghyanartur** [comment]
@MiltosD:

```
faceted_search_fields = {
    'category': {
        'field': 'category.raw',
        'enabled': True,
        'options': {
            "size": 20000,
            "order": {
                "_term": "asc"
            }
        },
    }
}
```
