### ISSUE TITLE
Wrong inner clas name in the quickstart documentation

### ISSUE THREAD

**Issue by AlekseiKhatkevich** [barseghyanartur/django-elasticsearch-dsl-drf#160]
In the documentation 
https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/docs/quick_start.rst#id36
in the  **Document definition**  section it should be:

`class Django(object):`

instead of 

`class Meta(object):`

**Comment by barseghyanartur** [comment]
@AlekseiKhatkevich:

Thanks. I thought it was already fixed once, but likely not. You're welcome to open a PR (and check other places as well). Otherwise, I'll do it some time later.

**Comment by barseghyanartur** [comment]
@AlekseiKhatkevich:

Thanks!
