### ISSUE TITLE
custom analyzer not work with the latest version of elastic search

### ISSUE THREAD

**Issue by raisulkutumbita** [barseghyanartur/django-elasticsearch-dsl-drf#164]
For fully test with elastic search 6.x, django-elastic-search-dsl 6.x custom analyzer works fine. But when I upgrade to 7.x for those its not work. Its Raise `BulkIndexError`.

**Comment by barseghyanartur** [comment]
@raisulkutumbita:

There have been changes between 6.x and 7.x affecting analyzers. However, example project is tested on both. Documentation might be outdated. Please, check the source (and eventually point me to parts of outdated documentation if found). In any case, if you upgrade from one version to another, you should rebuild your Elastic index completely.
