### ISSUE TITLE
Got "search_phase_execution_exception" while searching for full term

### ISSUE THREAD

**Issue by singhravi1** [barseghyanartur/django-elasticsearch-dsl-drf#168]
When i type the whole indexed term to search, I'm getting the following error trace. it works till you write the whole term. That too, for some of the terms. like, `top 10 iit jee coaching`

```
RequestError(400, 'search_phase_execution_exception', 'failed to create query: {\n "bool" : {\n "should" : [\n {\n "match" : {\n "term.synonyms" : {\n "query" : "top 10 iit jee coaching",\n "operator" : "OR",\n "prefix_length" : 0,\n "max_expansions" : 50,\n "fuzzy_transpositions" : true,\n "lenient" : false,\n "zero_terms_query" : "NONE",\n "auto_generate_synonyms_phrase_query" : true,\n "boost" : 30.0\n }\n }\n },\n {\n "match" : {\n "term" : {\n "query" : "top 10 iit jee coaching",\n "operator" : "OR",\n "prefix_length" : 0,\n "max_expansions" : 50,\n "fuzzy_transpositions" : true,\n "lenient" : false,\n "zero_terms_query" : "NONE",\n "auto_generate_synonyms_phrase_query" : true,\n "boost" : 1.0\n }\n }\n }\n ],\n "adjust_pure_negative" : true,\n "boost" : 1.0\n }\n}')
```

**To Reproduce**
1. Go to 'https://dev.edukhoj.com'
2. On the homepage, type in search bar, "top iit jee coaching"
3. Error will appear

**Expected behavior**
It should just show the search results as it does every other time.

**Additional context**
I'm using phonetic filter, with n-gram and synonyms filter
django-elasticsearch-dsl==0.5.1
django-elasticsearch-dsl-drf==0.17.6
elasticsearch-dsl==6.1.0

**Comment by barseghyanartur** [comment]
Try to upgrade your ``django-elasticsearch-dsl-drf`` and ``django-elasticsearch-dsl`` versions. AFAIK, ``django-elasticsearch-dsl`` does not work well with Elastic 6.x.

**Comment by singhravi1** [comment]
@barseghyanartur 
Which version do you suggest?
Should i change them to the latest ones?

**Comment by barseghyanartur** [comment]
Use the latest one of this library. As of ``django-elasticsearch-dsl`` - read the docs (of that one).

**Comment by singhravi1** [comment]
Hi @barseghyanartur,
I've updated the packages to the following versions,
```
django-elasticsearch-dsl==6.4.2
django-elasticsearch-dsl-drf==0.20.3
elasticsearch==6.4.0
elasticsearch-dsl==6.4.0

```
The elasticsearch server version i'm using is 6.8.0

**The said problem still persists.**

**Comment by barseghyanartur** [comment]
@singhravi1:

After update, your should rebuild your indexes.

**Comment by singhravi1** [comment]
@barseghyanartur 
Okay, did that just now. Still getting same error response.

**Comment by barseghyanartur** [comment]
@singhravi1:

That's strange.

I think you have misconfigured something. I can help you further, but that falls under premium support. Contact me by email for the details: https://github.com/barseghyanartur/django-elasticsearch-dsl-drf#author
