### ISSUE TITLE
Support for query_string filtering?

### ISSUE THREAD

**Issue by anryangelov** [barseghyanartur/django-elasticsearch-dsl-drf#169]
Is there any plans for implementing query_string (lucene_search) backend filtering?

**Comment by barseghyanartur** [comment]
Duplicate of https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/issues/65

**Comment by barseghyanartur** [comment]
There are plans, yes, however, I'm not sure when will I have time for it. You could, however, speed up the development by sponsoring this feature. Contact me for the details, if you wish.
