### ISSUE TITLE
The [standard] token filter has been removed

### ISSUE THREAD

**Issue by kanav220anand** [barseghyanartur/django-elasticsearch-dsl-drf#175]
BulkIndexError at /api/v1/posts/
('1 document(s) failed to index.', [{'index': {'_index': 'post', '_type': '_doc', '_id': '9', 'status': 400, 'error': {'type': 'illegal_argument_exception', 'reason': 'The [standard] token filter has been removed.'}, 'data': {'id': 9, 'title': 'test another 2', 'content': 'test new post'}}}])

**Comment by barseghyanartur** [comment]
You probably have something like this:

```
html_strip = analyzer(
    'html_strip',
    tokenizer="standard",
    filter=["standard", "lowercase", "stop", "snowball"],
    char_filter=["html_strip"]
)
```

Remove `standard` token from your definitions.
