### ISSUE TITLE
search by a substring in whole of the document 

### ISSUE THREAD

**Issue by kanav220anand** [barseghyanartur/django-elasticsearch-dsl-drf#176]
I am using postgres. Is there a way through which I can search by a substring in whole document? I have applied field_name__contains but that is not what I need. for eg. I search for "de". Then it should return me all users with names that contain de eg denis,wade as well as people who have designation containing "de" eg developer.
Also is there a way of consolidated search eg. de should search in all documents? 
Any help would be great. Thank You

**Comment by barseghyanartur** [comment]
You should clearly understand that there's no thing like "whole document". From what I understand from you - you need [multi match](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html). ``Multi match`` queries [are supported here](https://django-elasticsearch-dsl-drf.readthedocs.io/en/latest/search_backends.html#compound-search-filter-backend).
