### ISSUE TITLE
filter by OR

### ISSUE THREAD

**Issue by kanav220anand** [barseghyanartur/django-elasticsearch-dsl-drf#177]
Hi, I am trying to filter all the users that have profession and first_name as url/profession__contains=some&first_name=some but it returns the result using AND. Is there a way I can use to get the result as OR i.e get all those users which have either some as profession or some as name.
Thank You

**Comment by barseghyanartur** [comment]
Sure. What you need to do is to override the filter backend you're using and join results using AND instead of OR.

**Comment by kanav220anand** [comment]
I am using NestedFilterBackend.By default does it filter by AND or am I doing somethingwrong? Sorry I am new to programming. If I have to override the NestedFilterBackend which method should I override?
Thank You

**Comment by kanav220anand** [comment]
this is showing me results using AND and I want to get using OR. can you
tell me the name of function i need to override

**Comment by barseghyanartur** [comment]
Look for the `operator.or_` or `operator.and_`.
