### ISSUE TITLE
docker-compose up fails

### ISSUE THREAD

**Issue by jcushman** [barseghyanartur/django-elasticsearch-dsl-drf#178]
**Describe the bug**
`docker-compose up` currently fails on master because alpine linux doesn't use apt-get

**To Reproduce**

```
% docker-compose up
...
Building frontend
...
Step 1/9 : FROM docker.io/node:8-alpine3.9
 ---> b4f6d9bb0b68
Step 2/9 : RUN apt-get update
 ---> Running in 3de14dc0740e
/bin/sh: apt-get: not found
ERROR: Service 'frontend' failed to build: The command '/bin/sh -c apt-get update' returned a non-zero code: 127
```

Looks like this worked until the recent change to the frontend base image.

**Comment by barseghyanartur** [comment]
Fixed in master. Please check and let me know if it works for you.
