### ISSUE TITLE
Proper way of validating url query arguments against Document model

### ISSUE THREAD

**Issue by Vimdar** [barseghyanartur/django-elasticsearch-dsl-drf#181]
Hi, first of all thanks for the great package.

My question is what's the proper way to validate the request.query_params actually hit the fileds defined in django_elasticsearch_dsl.Document document used by a viewset?
Sadly browsing the docs and the existing issues did not led me to an answer/example.

    -Django==3.0.1
    -django-elasticsearch-dsl-drf==0.20.5
    -django-elasticsearch-dsl==7.1.1
    -djangorestframework==3.11.0

To simplify , I have a model (using one of the examples):

    class BookDocument(Document):
            title = KeywordField(
                 analyzer=html_strip,
                 fields={
                     'raw': fields.TextField(analyzer='keyword'),
                }
            )

and a viewset like:

    class BookDocumentView(BaseDocumentViewSet):
            document = BookDocument
            filter_backends = [
                FilteringFilterBackend,
            ]
            filter_fields = {
                'title': {
                    'field': 'title.raw',
                    'lookups': {
                        LOOKUP_QUERY_CONTAINS,
                       #  A_BUNCH_OF_OTHER_LOOKUP_CONSTANTS
                    }
                },
            }

Now if I query the app (urls are routed like the ezample app) at:

    http://localhost:8000/search/books/?title__contains=foo 

I'll get the results I need. But querying for a field non-existing in the document f. ex.

    http://localhost:8000/search/books/?bar__contains=foo 

will not modify queryset and viewset will end up executing the default one:

      "query": {
          "match_all": {}
        }
which will end up returning all documents for the index.

One could easily subclass and patch the filter_queryset() methods of desired django_elasticsearch_dsl_drf.filter_backends backends to:

    def filter_queryset(self, request, queryset, view):
        filter_query_params = self.get_filter_query_params(request, view)
        if not filter_query_params:
            raise NotFound(
                'No query parameters/No valid query parameters found!'
            )

or sth like that and bring on some more checks specific for the case.

Of course monkey patching each one of the default backends does not seem to be the right choice. So what's the proper way to ensure one's api will not return all documents if it receives a wrong query?
Thanks in advance!

**Comment by barseghyanartur** [comment]
Use your imagination. :) If you need validation, implement it yourself. I don't think you should bother validating non existent fields though.

If you come up with a great ideas and current backends stand in the way, I could add some additional abstraction level there.

Another option is to switch to graphql.

**Comment by barseghyanartur** [comment]
For the reference: https://pypi.org/project/graphene-elastic

**Comment by Vimdar** [comment]
Ok,
Thanks for the answer. The reason I wanted to validate the existence of those fields is getting all the data returned by default when querying for a non-existing field seems a bit counter-intuitive to me, since it refers with to a messed up query. What's more important though is now when I know it's purposely designed this way I can implement all the checks that ensure results I expect. And that is a good thing and a valuable insight I got from from this answer.

Using graphene-elastic is another way of doing this, but I think I'll stick to using Django and DRF cause they have some very handy out-of-the-box features that make sense for my purposes.

So I'm gonna go ahead and close the issue now, and leave it to archives for someone's future questions to be answered (if there any).
