### ISSUE TITLE
how to best decode url encoded query string?

### ISSUE THREAD

**Issue by prebenkeeeb** [barseghyanartur/django-elasticsearch-dsl-drf#182]
Since the django-elasticsearch-dsl-drf package passes the query string as query parameter then the query string should be url encoded e.g. if you search for: https://en.wikipedia.org/wiki/Coronavirus -> it becomes: https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FCoronavirus. 
I am using  FilteringFilterBackend and CompoundSearchFilterBackend and I noticed that query match string to elasticsearch is the encoded query string -> I want the url decode query string in order to get the right hits. How to best decode the query string? I assume I need to modify the backends?

**Comment by barseghyanartur** [comment]
Could you write a test case for this? In a fork. Let it fail first. If it's a valid test case, I'll fix that in master.

**Comment by barseghyanartur** [comment]
@prebenkeeeb:

Ping.

**Comment by prebenkeeeb** [comment]
I found out that normally django-elasticsearch-dsl-drf will url decode the query parameters. However the problem with the search string: "https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FCoronavirus" is that it contains a colon which is reserved to search in fields. As a workaround I now remove colons from the search string and everything seems to be ok. I do not have time to write any tests - sorry.
