### ISSUE TITLE
Is it possible to return non indexed fields in search results ?

### ISSUE THREAD

**Issue by girardinsamuel** [barseghyanartur/django-elasticsearch-dsl-drf#183]
**Question**

I have a model where I don't want to search in all fields but still i would like to display more fields than the fields which are "searchable" (ie the ones declared in the Document) in the results.

** What I tried **
* I tried to add fields in the serializer which are not in the Document but the field is not returned in the results. 
* I tried to add the field in the document and disable search for it but I did not find any attributes in the docs to do that.

I think I understand why it does not work because those fields I want to be returned are not stored in the index (in the source) so they can't be returned. Is there a workaround ? Like defining the field(s) in the document but disable the search for those fields ?

Thank you in advance !

**Comment by barseghyanartur** [comment]
I think you have misconfigured your app. Serializer is responsible for content of your response. The rest is just searching and filtering. If you don't want your field to appear in the results, remove it from serializer. That's all. Search, filtering and ordering backends (of this package) are not anyhow dependant on serializers.

**Comment by girardinsamuel** [comment]
I agree with you but that's not exactly what was my question about.
I will clarify quickly, here I don't want to remove fields from the results but I want to add fields in which I don't want to search. The basic option which is working is to add those fields in the documents but they will be indexed and use memory/resources. I was just asking if there was a better way.

I will give a real life example : we want to search in a list of contact (first name, last name, email for example). I would like to display the results as card with those three fields plus an avatar and a phone number => Is there another than adding the avatar and the phone number in the Elasticsearch document ?.

Because if I add those fields in the serializer but not in the document, an error will be thrown.

Is it more clear ? Am I reasoning wrong ?
Thank you again,

**Comment by barseghyanartur** [comment]
Look, if you want to add fields that are not searchable. The moment you add ES fields to ``search_fields``, ``filter_fields`` (of the view), etc - they become searchable, filterable, etc. Just do that. In principle, you can have all of your fields listed in the serializer and none of searchable.

There are many ways you can index data/fields in Elasticsearch, but you can also just store it (which means, data is not searchable/not_indexed).

**Comment by girardinsamuel** [comment]
I suppose that when you're saying "just store it", you're referring to the "store" feature of ES ?
https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-store.html

**Comment by barseghyanartur** [comment]
https://elasticsearch-dsl.readthedocs.io/en/2.2.0/persistence.html#mappings

``index='not_analyzed'``
