### ISSUE TITLE
how to add some operations between searching result and responsing the queryset?

### ISSUE THREAD

**Issue by ultimatedaotu** [barseghyanartur/django-elasticsearch-dsl-drf#184]
**Questions**
sorry I'm new to the lib and I got some problems.
In my task, I will do two steps of searching, the first is getting the queryset of ES, and then to do more operations on the results,  the subset of the result  may be what I need. What should I do?
1. do I need to over-wirte the function of get_queryset?
2 .I read the doc of django-elasticsaerch-dsl , it doesn't process the result of ES but make the sql search like "queryset = to_queryset(s)"  instead, should I do the same?

**Comment by barseghyanartur** [comment]
As far as I understand your issue, you want to do something with the results (like alter fields, etc). In Django REST Framework, that kind of staff you do in Serializers. Read official documentation of the Django REST Framework and extend your serializers the way you need.
