### ISSUE TITLE
How to do queries with MATCHING_OPTION_SHOULD?

### ISSUE THREAD

**Issue by EnriqueSoria** [barseghyanartur/django-elasticsearch-dsl-drf#185]
I want to boost documents with isParent=true instead of filtering by it.

Any idea what I'm missing or how can I achieve this?

## Expected behaviour
 * Documents with is_parent = true appear first 

## Actual behaviour
 * Only documents with is_parent = true are returned

## `views.py`
```
filter_fields = {
       ...
        'is_parent': {
            'field': 'is_parent',
            'lookups': [
                MATCHING_OPTION_SHOULD,
                MATCHING_OPTION_MUST,
            ],
        }
    }
```

## query
![imagen](https://user-images.githubusercontent.com/7394684/76958693-7c136980-6918-11ea-84a9-429c9e2fa9b5.png)

**Comment by barseghyanartur** [comment]
@EnriqueSoria:

I don't think you use proper wording. Boost is something else. If you search for something amount various fields in the same document and some fields have more weight than others, then you use boost.

As far as I understand what you want is sort/order your records by ``is_parent``. Fine, add it to the ordering filter and make it a default (first in the list). Search for ``ordering`` in the official documentation (of this package).
