### ISSUE TITLE
Search( size argument default : 10)

### ISSUE THREAD

**Issue by Allan-Nava** [barseghyanartur/django-elasticsearch-dsl-drf#187]
Is possible to serialized more than 10 elasticsearch data row? 

Because if I have a dataset of 15 row when I serialized with DOcumentSerialized it returns me 10 values

**Comment by barseghyanartur** [comment]
Use pagination. Read docs.

**Comment by Allan-Nava** [comment]
> Use pagination. [Read the docs](https://django-elasticsearch-dsl-drf.readthedocs.io/en/latest/advanced_usage_examples.html#pagination).

Thanks for the fastly answer, but i need to list more than 10 dataset.

I share u the code:
```
@action(methods=['get'], detail=True, permission_classes=[ IsAuthenticated ] )
 def societa(self, request, pk=None):
           sq      = SocietaCampionatoDocument.search().filter("term",
                societa__id=societa
            )
            squadre = SocietaCampionatoDocumentNoSocietaSerializer( sq , many=True ).data
            fdata = {
                "squadre"   : squadre,
            }
            return Response(fdata)

```

**Comment by barseghyanartur** [comment]
Try to stay close to the examples shown in the documentation.
