### ISSUE TITLE
Skip duplicate suggestions ?

### ISSUE THREAD

**Issue by akhan118** [barseghyanartur/django-elasticsearch-dsl-drf#189]
Hi and thank you all for your contributions .

Is there a way  to set Skip Duplicate Suggestions from django-elasticsearch-dsl-drf Views ?

Elastic Search Documentation said I can do this but I was wondering how to go about it on the Django side.

Skip duplicate suggestions
Queries can return duplicate suggestions coming from different documents. It is possible to modify this behavior by setting skip_duplicates to true. When set, this option filters out documents with duplicate suggestions from the result.

POST music/_search?pretty { "suggest": { "song-suggest" : { "prefix" : "nor", "completion" : { "field" : "suggest", "skip_duplicates": true } } } }

https://www.elastic.co/guide/en/elasticsearch/reference/master/search-suggesters.html#skip_duplicates

Thank you

**Comment by barseghyanartur** [comment]
@akhan118:

It should be simple to do by adding `skip_duplicates` option [here](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/src/django_elasticsearch_dsl_drf/filter_backends/suggester/native.py#L434) and enabling it in a way similar [to this](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/examples/simple/search_indexes/viewsets/book/frontend.py#L272).

Could you come up with a PR?

**Comment by akhan118** [comment]
Thank you . 

Will do, let me review the code tonight/weekends and test it and I'll be glad to push it .

**Comment by barseghyanartur** [comment]
@akhan118:

Thank you. Released in 0.20.7.

**Comment by akhan118** [comment]
Hey, I just updated and tested it and it wasn't working. I wasn't able to test it ealier because the Vagrant file was outdated .  Any idea why it's not working ?

**Comment by barseghyanartur** [comment]
You shouldn't be using Vagrant anymore. See [this](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/docs/installing_elasticsearch.rst). And don't forget to declare it in your viewset, as I mentioned earlier.

**Comment by akhan118** [comment]
Yeah I did declare it in the Viewset and testing it in production . However it still showing duplicate results. Did you test it from you end ? is working correctly from your end ? I would like to eliminate the fact it's not a bug or perhaps it is.

**Comment by barseghyanartur** [comment]
Please, check the query produced by Elasticsearch and post it here. It's easy to do using django-elastic toolbar.

**Comment by barseghyanartur** [comment]
Yep, something was missing. Check 0.20.8.

**Comment by akhan118** [comment]
Thanks, it's working as expected , I'll update the documentation soon .
