### ISSUE TITLE
No index created after following the quickstart

### ISSUE THREAD

**Issue by jfschaff** [barseghyanartur/django-elasticsearch-dsl-drf#191]
I followed the ["quick" start available here](https://django-elasticsearch-dsl-drf.readthedocs.io/en/latest/quick_start.html), but after running
```
./manage.py search_index --create -f
./manage.py search_index --populate -f
```
no index is created in elasticsearch. Also, as in #44, these two commands output nothing.

I must say that I have installed the module in an existing Django project, and tried to index existing models in my project. I'm using a PostgreSQL DB.

Here are some of my modules:
```
$ pip freeze
[...]
Django==2.2.11
django-elasticsearch-dsl==7.1.1
django-elasticsearch-dsl-drf==0.20.8
elasticsearch==7.6.0
elasticsearch-dsl==7.1.0
```

I also tried the [demo app here](https://django-elasticsearch-dsl-drf.readthedocs.io/en/latest/demo.html), the elasticseach docker image is ok, and the app installs and runs, but generates errors during install and then errors when any link is clicked...

How can I investigate what is going on?

**Comment by barseghyanartur** [comment]
@jfschaff:

Does cloning this project, installing [this](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/examples/requirements/elastic_7x.txt) and [this](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/examples/requirements/django_3_0.txt) reqs, running Elasticsearch 7 (like `docker-compose up elasticsearch` work for you?

**Comment by barseghyanartur** [comment]
BTW, `docker-compose up` works for me. I'll check the demo app installed (might be outdated).

**Comment by barseghyanartur** [comment]
In any case, creating  the index is out of the scope of the current library. Therefore, I close this ticket.

**Comment by barseghyanartur** [comment]
As someone mentionef in another issue, docs neef a slight update. Check the current examples dir, they are all up to date.

**Comment by barseghyanartur** [comment]
Guy, there's an [open issue](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/issues/73). Help is appreciated.
