### ISSUE TITLE
SuggesterFilterBackend not mapping to suggest endpoint

### ISSUE THREAD

**Issue by moldhouse** [barseghyanartur/django-elasticsearch-dsl-drf#196]
**Describe the bug**
I have Elasticsearch running on port 9200. I have an index 'Aircraft'. I am trying to get suggestion to work for that Index. I have created a simple AircraftDocument and AircraftSerializer, following the tutorial. In the Document, I have defined a CompletionField:

```
@INDEX.doc_type
class AircraftDocument(Document):
    """Aircraft Elasticsearch document."""
    name = fields.TextField(
        fields={
            'raw': fields.TextField(analyzer='keyword'),
            'suggest': fields.CompletionField(),
        } 
     )
    class Django(object):
        """Inner nested class Django."""

        model = Aircraft
        fields = (
            'id',
            'kind',
    )
```
In the view, I have:
```
class AircraftDocumentView(BaseDocumentViewSet):
    """The AircraftDocument view."""

    document = AircraftDocument
    serializer_class = AircraftDocumentSerializer
    pagination_class = PageNumberPagination
    lookup_field = 'id'
    filter_backends = [
        CompoundSearchFilterBackend,
        FilteringFilterBackend,
        IdsFilterBackend,
        OrderingFilterBackend,
        DefaultOrderingFilterBackend,
        SuggesterFilterBackend,
    ]
    suggester_fields = {
        'name_suggest': {
            'field': 'name_suggest',
            'suggesters': [
                SUGGESTER_COMPLETION,
            ],
            'options': {
                'size': 10,  # Override default number of suggestions
                'skip_duplicates': True, # Whether duplicate suggestions should be filtered out.
            },
        }
    }
```
I have checked with curl, and the corresponding mapping is created:

```
{
          "type" : "completion",
          "analyzer" : "simple",
          "preserve_separators" : true,
          "preserve_position_increments" : true,
          "max_input_length" : 50
        },
```
If I query ```localhost/search/aircraft/suggest/?name_suggest__completion=Pipe``` and
check the internally generated request, I get:

```curl -XGET 'http://localhost:9200/aircraft/_doc/suggest```

So somehow the url ending 'suggest' is put in place for the ID value which can not give any results. There seems to be some error in the url handling.

**Expected behavior**

Checking with curl, the request 
```
localhost:9200/aircraft/_search/
{
  "suggest":{
    "my-suggestion":{
      "prefix":"Pipe",
      "completion":{
        "field":"name_suggest"
      }
    }
  }
}
```
yields suggestions. 

**Additional context**
I am using:

django-elasticsearch-dsl==7.1.1
django-elasticsearch-dsl-drf==0.20.8
elasticsearch==7.6.0
elasticsearch-dsl==7.2.0

**Comment by barseghyanartur** [comment]
This should work as expected:

```
suggester_fields = {
        'name_suggest': {
            'field': 'name.suggest',
            'suggesters': [
                SUGGESTER_COMPLETION,
            ],
            'options': {
                'size': 10,  # Override default number of suggestions
                'skip_duplicates': True, # Whether duplicate suggestions should be filtered out.
            },
        }
    }
```

You're missing a dot.

**Comment by barseghyanartur** [comment]
P.S. Please, close the issue yourself if it's solved for you.

**Comment by moldhouse** [comment]
I actually changed this while debugging as I added a field name_suggest. Just to confirm, I changed it back to
```
suggester_fields = {
        'name_suggest': {
            'field': 'name.suggest',
            'suggesters': [
                SUGGESTER_COMPLETION,
            ],
            'options': {
                'size': 10,  # Override default number of suggestions
                'skip_duplicates': True, # Whether duplicate suggestions should be filtered out.
            },
        }
    }
``` 
and reindexed, but the issue still exists.

**Comment by moldhouse** [comment]
It does seem to be an issue with the url routing.

**Comment by barseghyanartur** [comment]
@moldhouse:

You should inherit from `DocumentViewSet` instead of `BaseDocumentViewSet`.

**Comment by Sachin-Kahandal** [comment]
@barseghyanartur Am having similar problem, my API is throwing Page not found for suggest. I already checked documentation and couldn't find it any helpful solving this issue.

Here is the link to StackoverFlow question
https://stackoverflow.com/questions/71754672/django-elasticsearch-dsl-drf-suggest-url-gives-404-page-not-found-error

Your help will be much appreciated.
