### ISSUE TITLE
Issue in suggestions

### ISSUE THREAD

**Issue by aviox-git** [barseghyanartur/django-elasticsearch-dsl-drf#198]
https://stackoverflow.com/questions/61769076/django-elasticsearch-dsl-drf-suggetions-issue

Urgent solution required. Please help.

**Comment by barseghyanartur** [comment]
@aviox-git : 

You should not be inheriting from `BaseDocumentViewSet`. Inherit from `DocumentViewSet` instead.

**Comment by barseghyanartur** [comment]
An explicit [note on this](https://django-elasticsearch-dsl-drf.readthedocs.io/en/latest/advanced_usage_examples.html?highlight=suggest#viewset-definition) is added to the docs.
