### ISSUE TITLE
OrderingFilterBackend with multiple ordering terms does not work

### ISSUE THREAD

**Issue by swilson11** [barseghyanartur/django-elasticsearch-dsl-drf#204]
**Describe the bug**
When using the OrderingFilterBackend, and supplying multiple fields in the ordering query parameter, all fields are ignored.

**To Reproduce**
1. Create a viewset that inherits from BaseDocumentViewSet
2. Supply an ordering fields dictionary with multiple keys
3. Submit a request with multiple valid values in the query parameter

**Expected behavior**
Results would be sorted by all terms supplied in the query parameter

**Additional context**
It seems that the problem is in parsing the query parameter.  The query parameter appears as a string, with multiple comma separated values in the string.  If you look in the core drf code (rest_framework/filters.py), in the OrderingFilter, the query parameter is parsed as follows:

        params = request.query_params.get(self.ordering_param)
        if params:
            fields = [param.strip() for param in params.split(',')]

However the dsl-drf filter is just taking the values and wrapping them in a list, instead of separating them at the commas. 

Thanks for the help and for creating this project.

**Comment by barseghyanartur** [comment]
Did you see/try [official documentation](https://django-elasticsearch-dsl-drf.readthedocs.io/en/latest/basic_usage_examples.html?highlight=ordering#ordering)?

``http://127.0.0.1:8080/search/publisher/?ordering=-country&ordering=city``

**Comment by swilson11** [comment]
Thanks for the fast reply! I missed the line in the docs about specifying ordering multiple times, sorry.  I am trying to replace an existing API using postgres with a new one using elasticsearch, same parameters, so was hoping to make everything match how drf works.  Also nice to be able to use with swagger. I'll try to add some code to convert to a list before it gets to the filter.
