### ISSUE TITLE
registry.update() to update specific field on a document

### ISSUE THREAD

**Issue by rootgrandfather** [barseghyanartur/django-elasticsearch-dsl-drf#205]
**Is your feature request related to a problem? Please describe.**
I use registry.update() to synchronously update elasticsearch document when a model instance changes,but this function always update all fields on the document,for example,a model blog has a field 'vcnt' to record the view counts,when a blog was viewed,the update action will be performed,but the document has a field containg the large content of the blog,this field also be updated,but i just want change the 'vcnt' field.
**Describe the solution you'd like**
When registry.update() performs update action between es document and django model,update the related or specific fields on the document.
**Describe alternatives you've considered**
Add an extra argument in function registry.update(),such as registry.update(update_fields=["xxx"]),to update the specific fields on a document.
**Additional context**
Related code.
![code](https://user-images.githubusercontent.com/30030633/84593105-c86d3780-ae7c-11ea-96ae-e85157f6ea67.png)

**Comment by barseghyanartur** [comment]
Could you raise your question in the django-elasticsearch-dsl?
