### ISSUE TITLE
How to access the actual count of the query results?

### ISSUE THREAD

**Issue by rmiaas** [barseghyanartur/django-elasticsearch-dsl-drf#207]
Hi @barseghyanartur ,

Using elastic_panel and django-debug-toolbar, i noticed that a `_count` query is done for the actual count. Is there any way i can access the actual count? The paginated count from the serializer is `hits.total.value`, which makes sense. However, i want to access the actual count too in my use case. Any help would be appreciated. Thanks!
<img width="947" alt="snip" src="https://user-images.githubusercontent.com/34234631/85258755-90787c80-b49a-11ea-84e9-cb42b5a31583.png">

**Comment by barseghyanartur** [comment]
Since counts are added in the pagination and that part is flexible, you could override pagination class and add desired info there.

**Comment by rmiaas** [comment]
Thanks for such a quick response!
