### ISSUE TITLE
Assigning m2m relationship during tests is updating my index

### ISSUE THREAD

**Issue by adl-asi** [barseghyanartur/django-elasticsearch-dsl-drf#208]
I'm running tests that are assigning m2m relationships on a model that i am indexing for elasticsearch. I have completely removed my post save signal that updates instance on the index and it is still happening. Please help

**Comment by adl-asi** [comment]
Thanks

If anyone finds this and is wondering how add this into your settings file:
ELASTICSEARCH_DSL_AUTOSYNC = False

**Comment by barseghyanartur** [comment]
> Thanks
> 
> If anyone finds this and is wondering how add this into your settings file:
> ELASTICSEARCH_DSL_AUTOSYNC = False

I'll add this to FAQ. Thank you!
