### ISSUE TITLE
Create and update method for DocumentSerializer

### ISSUE THREAD

**Issue by yekmolsoheil** [barseghyanartur/django-elasticsearch-dsl-drf#210]
Hi Sir. I wanted to ask about the create and update methods of DocumentSerializer in your package. should it be implemented by the user for each document? why this doesn't have something default like drf's ModelSerializers to handle this issue automatically?

And if i should develop that part of code myself, how should it be implemented. is there any examples?

**Comment by barseghyanartur** [comment]
You misunderstood quite a lot. Study django-eladticsearch-dsl docs.

TL;DR

You are not supposed to write to elasticsearch using this package.

**Comment by yekmolsoheil** [comment]
Oh thanks. Is there any other options to do so?

**Comment by barseghyanartur** [comment]
Did you actually dive into django-elasticsearch-dsl? And what are you trying to achieve (the big picture)?
