### ISSUE TITLE
@admin.register(Book) NameError: name 'Book' is not defined

### ISSUE THREAD

**Issue by Gr4vity0** [barseghyanartur/django-elasticsearch-dsl-drf#211]
**Questions**

Hi, 

Thanks for this doc it's great to follow it step by step but:

I have a problem with the example app (https://django-elasticsearch-dsl-drf.readthedocs.io/en/latest/quick_start.html#example-app).

I literally copied/paste the code after write it by hand all day but I can't migrate the models...

File "/home/gr4vity0/Desktop/python/elasticfinal/books/admin.py", line 6, in <module>
    @admin.register(Book)
NameError: name 'Book' is not defined

You can check my code here : https://github.com/Gr4vity0/elasticbooks

Thank you ;)

**Comment by barseghyanartur** [comment]
You didn't define a Book model. But in general, this kind of questions are not welcome.
