### ISSUE TITLE
DateField format issue

### ISSUE THREAD

**Issue by kanav220anand** [barseghyanartur/django-elasticsearch-dsl-drf#214]
The datefield is producing some funny results. I have set the datetime format in settings file as '%Y-%m-%dT%H:%M:%SZ' and in normal api calls it works as expected("2020-10-20T05:13:33Z")  but the same object when searched gives output as "2020-10-20T05:13:33.594142+00:00". Is there anything that can be done about it?

**Comment by barseghyanartur** [comment]
@kanav220anand:

Good question. This is how you solve it, if formatting matters to you.

- [Updated Django model definition](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/examples/simple/books/models/book.py#L77).
- [Updated document definition](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/examples/simple/search_indexes/documents/book.py#L159).
