### ISSUE TITLE
Add setting to define default Pagination class

### ISSUE THREAD

**Issue by javiermatos** [barseghyanartur/django-elasticsearch-dsl-drf#215]
I am using DRF with LimitOffsetPagination. It is set as the default class by doing `REST_FRAMEWORK['DEFAULT_PAGINATION_CLASS'] = 'rest_framework.pagination.LimitOffsetPagination'` in my settings file.

Now that I am using this project I would like to have a similar setting so I can set a global pagination. I do not want to add a `pagination_class` attribute per class inheriting from `BaseDocumentViewSet`, but just do it using a global setting.

Easiest way could be to just define a settings parameter that can be overwritten as with `REST_FRAMEWORK` while using DRF. You actually have a constants.py file that can hold that setting.

**Comment by barseghyanartur** [comment]
There are no settings ATM. Constants is used as something else. Default pagination class is `PageNumberPagination`. I think in your case, I would define another `BaseDocumentViewSet` or `DocumentViewSet` (as in [viewsets](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/src/django_elasticsearch_dsl_drf/viewsets.py)), override your `pagination_class` there and use it in project.

**Comment by javiermatos** [comment]
Thank you. I am already using that `DocumentViewSet` as base for my views. And thank you for creating this project. It is really useful!
