### ISSUE TITLE
Tests incompatible with factory_boy 3

### ISSUE THREAD

**Issue by jayvdb** [barseghyanartur/django-elasticsearch-dsl-drf#217]
`from factory import DjangoModelFactory` now needs to be from `factory.django import DjangoModelFactory`

**Comment by barseghyanartur** [comment]
@jayvdb:

Already solved in the master.

**Comment by jayvdb** [comment]
Thanks for https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/pull/228
