### ISSUE TITLE
Is it possible to 'rebuild' only one index ?

### ISSUE THREAD

**Issue by akhan118** [barseghyanartur/django-elasticsearch-dsl-drf#223]
Hi There,

currently `python manage.py search_index --rebuild`, deletes all index and repopulate them.

is it possible to specify which index to rebuild instead of all?

Thank you

**Comment by barseghyanartur** [comment]
@akhan118:

Question is not to me, but to [django-elasticsearch-dsl](https://github.com/django-es/django-elasticsearch-dsl). Some time ago it was not yet implemented. Please, check yourself. In any case, implementing that feature would not be difficult.
