### ISSUE TITLE
How to generate proper auto-documentation ?

### ISSUE THREAD

**Issue by yleclanche** [barseghyanartur/django-elasticsearch-dsl-drf#226]
**Questions**

Hello, I'm trying to documente my API.
I made a viewset. In DRF documentation, my filters appear like this without any description :
![image](https://user-images.githubusercontent.com/870719/105711740-40263900-5f19-11eb-8cf4-50d6ea3ecaa0.png)

Is there any way to set a description ? 
I searched in the code and didn't find a way, so I made my own patch in `common.py` : 

```   
def get_coreschema_field(self, field, filter_fields={}):
        if isinstance(field, fields.IntegerField):
            field_cls = coreschema.Number
        else:
            field_cls = coreschema.String
        params = {}
        value = filter_fields.get('description')
        if value:
            params['description'] = value
        return field_cls(**params)

 def get_schema_fields(self, view):
        assert coreapi is not None, 'coreapi must be installed to ' \
                                    'use `get_schema_fields()`'
        assert coreschema is not None, 'coreschema must be installed to ' \
                                       'use `get_schema_fields()`'
        filter_fields = getattr(view, 'filter_fields', None)
        document = getattr(view, 'document', None)


        return [] if not filter_fields else [
            coreapi.Field(
                name=field_name,
                required=False,
                location='query',
                schema=self.get_coreschema_field(
                    document._fields.get(field_name),
                    filter_fields[field_name]
                )
            )
            for field_name in filter_fields
        ]
```

So now I just have to set `description` in filter : 
```
'price': {
        'field': 'price',
        'description':"My custom description",
}
```

It works, but is there a proper way to do this ?

**Comment by barseghyanartur** [comment]
Every filter backend should have [something like this](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/src/django_elasticsearch_dsl_drf/filter_backends/filtering/common.py):

```python
# ...
    def get_coreschema_field(self, field):
        if isinstance(field, fields.IntegerField):
            field_cls = coreschema.Number
        else:
            field_cls = coreschema.String
        return field_cls()

    def get_schema_fields(self, view):
        assert coreapi is not None, 'coreapi must be installed to ' \
                                    'use `get_schema_fields()`'
        assert coreschema is not None, 'coreschema must be installed to ' \
                                       'use `get_schema_fields()`'
        filter_fields = getattr(view, 'filter_fields', None)
        document = getattr(view, 'document', None)

        return [] if not filter_fields else [
            coreapi.Field(
                name=field_name,
                required=False,
                location='query',
                schema=self.get_coreschema_field(
                    document._fields.get(field_name)
                )
            )
            for field_name in filter_fields
        ]
# ...
```

Ordering filter backend [has it too](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/src/django_elasticsearch_dsl_drf/filter_backends/ordering/common.py#L177).

Schema generation is [covered with tests](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/src/django_elasticsearch_dsl_drf/tests/test_filtering_common.py#L664).

If you have time on this, please, do check if this is applicable to all filter backends. If not, please at least let me know (just here). Direct PRs with fixes are more than welcome (if you happen to find something missing).

**Comment by barseghyanartur** [comment]
@yleclanche 

Did you manage to generate the docs? Any observations to share?

**Comment by yleclanche** [comment]
@barseghyanartur Yes, but I only tested with filters. Like you said, it would be great if it works for ordering too but I don't have time for the moment.
