### ISSUE TITLE
post_delete signal not working

### ISSUE THREAD

**Issue by hagen00** [barseghyanartur/django-elasticsearch-dsl-drf#235]
I am following the docs as per this: https://django-elasticsearch-dsl-drf.readthedocs.io/en/0.2.6/quick_start.html#id32

The `post_save` signal is working fine. When a "tag" entry is updated, ES is updated as well. 

However, when using post_delete, and deleting the "tag" entry, then ES is not updated. 
`instance.articles.all()` is returning empty. 

The code for post_save and post_delete is almost identical. 

Can someone confirm that this is indeed a bug? I can't see what I'm doing wrong.

**Comment by barseghyanartur** [comment]
First of all, always use [latest](https://django-elasticsearch-dsl-drf.readthedocs.io/en/latest/quick_start.html#id32).

Secondly, that part is done by [django-elasticsearch-dsl](https://github.com/django-es/django-elasticsearch-dsl), so you better raise a ticket there.
