### ISSUE TITLE
Is there a way to create custom search backends ?

### ISSUE THREAD

**Issue by dorin-musteata** [barseghyanartur/django-elasticsearch-dsl-drf#236]
Haven't found an example how to create custom search backend. Basically I want to create a search backend to search with _like_  operator like in SQL

**?search=query** which will translate to **%query%** , I know there is _contains_ , _wildcard_ , etc , but I want to make it part of **?search** query parameter.

Thanks , for this great project.

**Comment by Sachin-Kahandal** [comment]
@barseghyanartur Thanks for this amazing package, I just have a doubt I want to use multi_match, match_phrase and simple search altogether in the same search. 

For Example: 
query0 = MultiMatch(query=text, analyzer= "stop", fields=['Info^2.5', 'Title'], operator="AND", fuzziness='AUTO')
tquery1 = Match(Title={'query': text, "analyzer": "stop", 'operator': 'and', 'boost': '1.5'})
dquery1 = Match(Description={'query': text, "analyzer": "stop", 'operator': 'and', 'boost': '1.2'})
tquery2 = Match(Title={'query': text, "analyzer": "stop", 'minimum_should_match': '3<75%'})
tquery3 = MatchPhrase(Title={'query': text, "analyzer": "stop", 'boost': '1.5'})
dquery3 = MatchPhrase(Description={'query': text, "analyzer": "stop", 'boost': '1.5'})
item_url_query = Match(Item_url={'query': text, "analyzer": "stop", 'operator': 'and', 'boost': '2.8'})
q = Bool(should=[query0, tquery1, dquery1, tquery2, tquery3, dquery3, item_url_query])
s = Search(index=index).query(q).extra(min_score=15)
result = s.execute()

Now this is what I was doing in my django web app, combining multiple queries and the results were pretty good.

Right now, to use multi_match search I got to use "search_multi_match" param, for match got to use "search", while I want to use all these queries while using just search parameter

Is there any way to achieve this? Or Do I have to create custom backend? If yes, any tips?
