### ISSUE TITLE
Multi term search issue

### ISSUE THREAD

**Issue by toluaina** [barseghyanartur/django-elasticsearch-dsl-drf#24]
It appears a bug was introduced in this commit b397c49d797e8a4da0ce03dba0056a5798e095b0
line 119 - `field, value = __values` needs to be outside the if statement.

Errors : with field is used before assignment

regards

--Tolu

**Comment by barseghyanartur** [comment]
@toluaina:

Thanks for bringing this up. It solved in 0.6.3.

**Comment by toluaina** [comment]
Thanks for the quick fix.

Really great library by the way. I found it very easy to use.


On an unrelated note, is it possible to do partial search across all fields or across a list of predefined fields.


kind regards,


--Tolu


________________________________

**Comment by barseghyanartur** [comment]
@toluaina:

As mentioned in the [docs](http://django-elasticsearch-dsl-drf.readthedocs.io/en/0.6.3/#main-features-and-highlights), a large variety of Elastic filters is supported. For partial search you should probably be using ``endswith``, ``contains``, ``wildcard``, ``prefix`` (same as ``startswith``) filters.

That part isn't that well documented. You can see how it's done in [tests](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/src/django_elasticsearch_dsl_drf/tests/test_filtering_common.py).

Search for correspondent filter in the code.

Good luck!

**Comment by toluaina** [comment]
Thanks once again. This is perfect and almost what i was looking for.


Is it possible to OR the filters instead of AND.



e.g I would like to do something like


http://localhost:8000/books/?title__contains=foo|author__contains=bar


Also is there an easy way to enforce lowercasing all terms so i can also do as well


http://localhost:8000/books/?title__contains=Foo|author__contains=Bar


thanks once again.






--Tolu


________________________________

**Comment by barseghyanartur** [comment]
@toluaina:

- OR/AND - not yet. As a workaround, you could make a separate index that would contain both (or all the fields that should be searched in).
- No, but you could override any of the backends and make the changes necessary.
