### ISSUE TITLE
BaseDocumentViewSet.get_object does not provide access to meta.id

### ISSUE THREAD

**Issue by selimt** [barseghyanartur/django-elasticsearch-dsl-drf#242]
Hi, I am trying to find a way to include the document id in the response. For list actions I am able to do this by declaring my "id" field in the serializer as follows:

```
class MySerializer(DocumentSerializer):
    id = SerializerMethodField()

    class Meta:
        fields = ('id',...)

    def get_id(self, instance):
        return instance.meta.id
```

Unfortunately this doesn't work for a detail action since the base viewset code wraps the object's source fields only with the DictionaryProxy so the id doesn't get included.

**Comment by barseghyanartur** [comment]
@selimt:

Check [this](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/examples/simple/search_indexes/serializers/city.py#L33). Works (fixed) in the master ATM, but will make into the release soon.

**Comment by selimt** [comment]
@barseghyanartur It seems to work great! Thanks for this.

**Comment by barseghyanartur** [comment]
@selimt:

FYI, release 0.22.1 has the fix.
