### ISSUE TITLE
Pagination in Function Based Views with Slicing

### ISSUE THREAD

**Issue by Jack-24** [barseghyanartur/django-elasticsearch-dsl-drf#252]
**Is your feature request related to a problem? Please describe.**
This is a request related to a problem in the paginator in function based views.

**Describe the solution you'd like**
It should be possible to do the following. Right now, this would give an error as it seems to only work in class based views.

```
paginator    = PageNumberPagination()
queryset      = paginator.paginate_queryset(queryset, request)
outputData = TestDocumentSerializer(queryset, many=True).data
return paginator.get_paginated_response(outputData)
```
**Describe alternatives you've considered**
Using the paginator of Django Rest Framework works but it does not support slicing of the queryset before pagination.

**Comment by barseghyanartur** [comment]
I don't think function based views will ever be supported. Therefore, it's out of the scope.
