### ISSUE TITLE
Cannot Import ObjectDocumentSerializer in my Console

### ISSUE THREAD

**Issue by yusufselimkaratas** [barseghyanartur/django-elasticsearch-dsl-drf#254]
**Questions**

Dear All,

I am trying to step into Elastic Search with Django. I tried to follow quickstart part and I have written a documentserializer.

        class AgencyNewsDocumentSerializer(DocumentSerializer):

        class Meta:

            document = AgencyNewsDocument

           fields = (

                  'id',
                  'title',
                  'headline',
                  'text',
        )

and I can not import it from my Python Console.

ImportError: cannot import name 'AgencyNewsDocumentSerializer' from 'news.serializers'

What may be the reason. I can import other django serializers on the same .py document.

**Comment by barseghyanartur** [comment]
No idea. There should be some misconfiguration on your side, but it's hard to tell what without the context.

**Comment by yusufselimkaratas** [comment]
I can not still import it in my Python Console, But  serializer works as it needs to do when I send request from Postman.

 Strange.

But no need to keep the issue open since it works in Postman.

I close the issue
