### ISSUE TITLE
PageNumberPagination returns null for count when using EmptySearch

### ISSUE THREAD

**Issue by alexgmin** [barseghyanartur/django-elasticsearch-dsl-drf#255]
**Describe the bug**

In https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/issues/238 support for EmptySearch was added.
This works correctly except for one small detail, the count in the response is null instead of 0.
This is an issue for two reasons:
- Using an EmptySearch means that you want to return the equivalent of an empty list to the user, returning null instead of 0 means that there's a difference in behavior.
- It is invalid according the schema defined by drf, which indicates that count is not nullable.
https://github.com/encode/django-rest-framework/blob/61e7a993bd0702d30e3049179000bc7c5f284781/rest_framework/pagination.py#L232-L240

The workaround we're currently using is to set this:
`self.paginator.page.count = 0`
Between the calls to `paginate_queryset()` and `get_paginated_response()`

**Comment by barseghyanartur** [comment]
@alexgmin:

Thanks for reporting. I'll check it ASAP.

**Comment by ijharulislam** [comment]
Is there any update here?

**Comment by vanovarderesyan** [comment]
Hi everyone, this issue is still actual, which kind of alternate would you offer for this? Or the best solution is to write things from scratch?

**Comment by barseghyanartur** [comment]
Fixed in the master. Will be released soon.

**Comment by barseghyanartur** [comment]
Fixed in 0.22.5.
