### ISSUE TITLE
Migrate to GitHub actions

### ISSUE THREAD

**Issue by barseghyanartur** [barseghyanartur/django-elasticsearch-dsl-drf#256]

**Comment by tanvimoharir** [comment]
Hi,
I would like to work on this,
Thanks

**Comment by barseghyanartur** [comment]
@tanvimoharir:

Please, do. I like [this structure](https://github.com/barseghyanartur/valuta/blob/master/.github/workflows/test.yml) (matches the needs of most of the projects I worked on). Although, better ideas are welcome. A couple of TODOs (not yet clear to me): how to make it nicely integrate with coveralls.io. Please, work in a branch. Contact me for a key to coveralls.io (when needed), but I consider that a "part 2". What's most important, is to test against both ES6 and ES7 as long as they are supported by this package (latest releases from both branches).

**Comment by barseghyanartur** [comment]
P.S.

For this project, retry feature is important (used to happen with travis sometimes that once in a while, some test would fail and re-running it would fix the problem). If no alternative feature exists on the GitHub actions side, there's a pytest plugin doing the same thing.

**Comment by tanvimoharir** [comment]
> @tanvimoharir:
> 
> Please, do. I like [this structure](https://github.com/barseghyanartur/valuta/blob/master/.github/workflows/test.yml) (matches the needs of most of the projects I worked on). Although, better ideas are welcome. A couple of TODOs (not yet clear to me): how to make it nicely integrate with coveralls.io. Please, work in a branch. Contact me for a key to coveralls.io (when needed), but I consider that a "part 2". What's most important, is to test against both ES6 and ES7 as long as they are supported by this package (latest releases from both branches).

Sure, I will start following this structure from a different branch. You should be adding the keys directly as secrets (Refer https://docs.github.com/en/actions/reference/encrypted-secrets) and I can include the variable name itself.

**Comment by tanvimoharir** [comment]
@barseghyanartur  I could not create a branch on the repo so I forked it.
I have added a workflow but I might need to make some changes.

**Comment by barseghyanartur** [comment]
@tanvimoharir:

Yep, that's a very valid question. Is it possible to run Elasticsearch on GitHub actions?

**Comment by barseghyanartur** [comment]
A tiny update. I figured out how to make Coveralls work with GitHub actions.

**Comment by barseghyanartur** [comment]
Works in master.

**Comment by barseghyanartur** [comment]
Again, thanks @Andrew-Chen-Wang and @tanvimoharir.
