### ISSUE TITLE
SUGGESTER_TERM and SUGGESTER_PHRASE does not return results.

### ISSUE THREAD

**Issue by yotovtsvetomir** [barseghyanartur/django-elasticsearch-dsl-drf#267]
SUGGESTER_TERM and SUGGESTER_PHRASE does not return results. I have copy/pasted the code from https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/docs/advanced_usage_examples.rst#term

Whatever I do i get empty array in the options. Any ideas?

**Comment by barseghyanartur** [comment]
You should make sure you have indexed things properly. Otherwise, you won't get results. Please, take a deeper look at the examples.

**Comment by yotovtsvetomir** [comment]
I tried, but the result is always empty list.

here is my code:

`from elasticsearch_dsl import analyzer
from elasticsearch_dsl.analysis import token_filter
from django_elasticsearch_dsl import Document, Index, fields
from django_elasticsearch_dsl.registries import registry
from products.models import *
from django.conf import settings

html_strip = analyzer(
    'html_strip',
    tokenizer="standard",
    filter=["lowercase", "stop", "snowball"],
    char_filter=["html_strip"]
)


# Name of the Elasticsearch index
product_index = Index('product')
# See Elasticsearch Indices API reference for available settings
product_index.settings(
    number_of_shards=1,
    number_of_replicas=1
)

@product_index.doc_type
class ProductDocument(Document):
    id = fields.IntegerField()
    title = fields.TextField(
        analyzer=html_strip,
        fields={
            'raw': fields.KeywordField(),
            'suggest': fields.CompletionField(),
        }
    )`

and this is my viewset:
`class ElasticProduct(DocumentViewSet):
    document = ProductDocument
    serializer_class = ProductDocumentSerializer

    filter_backends = [
        DefaultOrderingFilterBackend,
        OrderingFilterBackend,
        FilteringFilterBackend,
        CompoundSearchFilterBackend,
        SuggesterFilterBackend
    ]

    ordering = ('_score', 'sold', 'rating', '-discount')

    ordering_fields = {
        'id': 'id',
        'price': 'price',
        'created': 'created',
        'sold': 'sold',
        'discount': 'discount',
        'rating': 'rating',
        'viewed': 'viewed'
    }

    search_fields = {
        'title': 'title.raw',
        'description': 'description',
        'brand': 'brand'
    }

    filter_fields = {
        'price': {
            'field': 'price',
            'lookups': [
                LOOKUP_FILTER_RANGE,
                LOOKUP_QUERY_IN,
                LOOKUP_QUERY_GT,
                LOOKUP_QUERY_GTE,
                LOOKUP_QUERY_LT,
                LOOKUP_QUERY_LTE,
            ],
        },
        'created': {
            'field': 'created',
            'lookups': [
                LOOKUP_FILTER_RANGE,
                LOOKUP_QUERY_IN,
                LOOKUP_QUERY_GT,
                LOOKUP_QUERY_GTE,
                LOOKUP_QUERY_LT,
                LOOKUP_QUERY_LTE,
            ],
        },
        'viewed': {
            'field': 'viewed',
            'lookups': [
                LOOKUP_FILTER_RANGE,
                LOOKUP_QUERY_IN,
                LOOKUP_QUERY_GT,
                LOOKUP_QUERY_GTE,
                LOOKUP_QUERY_LT,
                LOOKUP_QUERY_LTE,
            ],
        },
        'rating': {
            'field': 'rating',
            'lookups': [
                LOOKUP_FILTER_RANGE,
                LOOKUP_QUERY_IN,
                LOOKUP_QUERY_GT,
                LOOKUP_QUERY_GTE,
                LOOKUP_QUERY_LT,
                LOOKUP_QUERY_LTE,
            ],
        },
        'promo_price': {
            'field': 'promo_price',
            'lookups': [
                LOOKUP_FILTER_RANGE,
                LOOKUP_QUERY_IN,
                LOOKUP_QUERY_GT,
                LOOKUP_QUERY_GTE,
                LOOKUP_QUERY_LT,
                LOOKUP_QUERY_LTE,
            ],
        },
        'title': {
            'field': 'title',
            'lookups': [
                LOOKUP_FILTER_TERMS,
                LOOKUP_FILTER_PREFIX,
                LOOKUP_FILTER_WILDCARD,
                LOOKUP_QUERY_IN,
                LOOKUP_QUERY_EXCLUDE,
                LOOKUP_QUERY_ISNULL,
            ]
        },
        'brand': {
            'field': 'brand.brand',
            'lookups': [
                LOOKUP_FILTER_TERMS,
                LOOKUP_FILTER_PREFIX,
                LOOKUP_FILTER_WILDCARD,
                LOOKUP_QUERY_IN,
                LOOKUP_QUERY_EXCLUDE,
                LOOKUP_QUERY_ISNULL,
            ]
        },
        'maker': {
            'field': 'maker.raw',
            'lookups': [
                LOOKUP_FILTER_TERMS,
                LOOKUP_FILTER_PREFIX,
                LOOKUP_FILTER_WILDCARD,
                LOOKUP_QUERY_IN,
                LOOKUP_QUERY_EXCLUDE,
                LOOKUP_QUERY_ISNULL,
            ]
        },
        'categories': {
            'field': 'categories.id',
            'lookups': [
                LOOKUP_FILTER_RANGE,
                LOOKUP_QUERY_IN,
                LOOKUP_QUERY_GT,
                LOOKUP_QUERY_GTE,
                LOOKUP_QUERY_LT,
                LOOKUP_QUERY_LTE,
            ]
        },
        'slug': 'slug.raw',
        'merchant':'merchant.id',
        'active': 'active',
        'deleted': 'deleted'
    }

    suggester_fields = {
        'title_suggest': {
            'field': 'title.suggest',
            'suggesters': [
                SUGGESTER_COMPLETION,
                SUGGESTER_TERM,
                SUGGESTER_PHRASE,
            ],
            'default_suggester': SUGGESTER_COMPLETION,
            'options': {
                'size': 10,  # Number of suggestions to retrieve.
                'skip_duplicates':True, # Whether duplicate suggestions should be filtered out.
            },
        },
    }`

Any ideas? Thank you.

**Comment by yotovtsvetomir** [comment]
Everything was working perfectly. I didn't know that the term or phrase **MUST** have typo, example: Laptpo
