### ISSUE TITLE
RequestError when i am trying to search strings

### ISSUE THREAD

**Issue by antl31** [barseghyanartur/django-elasticsearch-dsl-drf#268]
Hello, i have error when i tried to search string.
 `    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'failed to create query: {\n  "bool" : {\n    "should" : [\n      {\n        "match" : {\n          "name" : {\n            "query" : "ure",\n            "operator" : "OR",\n            "prefix_length" : 0,\n            "max_expansions" : 50,\n            "fuzzy_transpositions" : true,\n            "lenient" : false,\n            "zero_terms_query" : "NONE",\n            "auto_generate_synonyms_phrase_query" : true,\n            "boost" : 1.0\n          }\n        }\n      },\n      {\n        "match" : {\n          "organization" : {\n            "query" : "ure",\n            "operator" : "OR",\n            "prefix_length" : 0,\n            "max_expansions" : 50,\n            "fuzzy_transpositions" : true,\n            "lenient" : false,\n            "zero_terms_query" : "NONE",\n            "auto_generate_synonyms_phrase_query" : true,\n            "boost" : 1.0\n          }\n        }\n      },\n      {\n        "match" : {\n          "Venture_Capital_Investor" : {\n            "query" : "ure",\n            "operator" : "OR",\n            "prefix_length" : 0,\n            "max_expansions" : 50,\n            "fuzzy_transpositions" : true,\n            "lenient" : false,\n            "zero_terms_query" : "NONE",\n            "auto_generate_synonyms_phrase_query" : true,\n            "boost" : 1.0\n          }\n        }\n      },\n      {\n        "match" : {\n          "Transaction_type" : {\n            "query" : "ure",\n            "operator" : "OR",\n            "prefix_length" : 0,\n            "max_expansions" : 50,\n            "fuzzy_transpositions" : true,\n            "lenient" : false,\n            "zero_terms_query" : "NONE",\n            "auto_generate_synonyms_phrase_query" : true,\n            "boost" : 1.0\n          }\n        }\n      },\n      {\n        "match" : {\n          "Date" : {\n            "query" : "ure",\n            "operator" : "OR",\n            "prefix_length" : 0,\n            "max_expansions" : 50,\n            "fuzzy_transpositions" : true,\n            "lenient" : false,\n            "zero_terms_query" : "NONE",\n            "auto_generate_synonyms_phrase_query" : true,\n            "boost" : 1.0\n          }\n        }\n      },\n      {\n        "match" : {\n          "Type" : {\n            "query" : "ure",\n            "operator" : "OR",\n            "prefix_length" : 0,\n            "max_expansions" : 50,\n            "fuzzy_transpositions" : true,\n            "lenient" : false,\n            "zero_terms_query" : "NONE",\n            "auto_generate_synonyms_phrase_query" : true,\n            "boost" : 1.0\n          }\n        }\n      },\n      {\n        "match" : {\n          "is_lead_investor" : {\n            "query" : "ure",\n            "operator" : "OR",\n            "prefix_length" : 0,\n            "max_expansions" : 50,\n            "fuzzy_transpositions" : true,\n            "lenient" : false,\n            "zero_terms_query" : "NONE",\n            "auto_generate_synonyms_phrase_query" : true,\n            "boost" : 1.0\n          }\n        }\n      },\n      {\n        "match" : {\n          "Local_Currency" : {\n            "query" : "ure",\n            "operator" : "OR",\n            "prefix_length" : 0,\n            "max_expansions" : 50,\n            "fuzzy_transpositions" : true,\n            "lenient" : false,\n            "zero_terms_query" : "NONE",\n            "auto_generate_synonyms_phrase_query" : true,\n            "boost" : 1.0\n          }\n        }\n      },\n      {\n        "match" : {\n          "Money_Raised_local" : {\n            "query" : "ure",\n            "operator" : "OR",\n            "prefix_length" : 0,\n            "max_expansions" : 50,\n            "fuzzy_transpositions" : true,\n            "lenient" : false,\n            "zero_terms_query" : "NONE",\n            "auto_generate_synonyms_phrase_query" : true,\n            "boost" : 1.0\n          }\n        }\n      },\n      {\n        "match" : {\n          "FX_Rate" : {\n            "query" : "ure",\n            "operator" : "OR",\n            "prefix_length" : 0,\n            "max_expansions" : 50,\n            "fuzzy_transpositions" : true,\n            "lenient" : false,\n            "zero_terms_query" : "NONE",\n            "auto_generate_synonyms_phrase_query" : true,\n            "boost" : 1.0\n          }\n        }\n      },\n      {\n        "match" : {\n          "Money_Raised_USD" : {\n            "query" : "ure",\n            "operator" : "OR",\n            "prefix_length" : 0,\n            "max_expansions" : 50,\n            "fuzzy_transpositions" : true,\n            "lenient" : false,\n            "zero_terms_query" : "NONE",\n            "auto_generate_synonyms_phrase_query" : true,\n            "boost" : 1.0\n          }\n        }\n      },\n      {\n        "match" : {\n          "Pre_Money_Valuation" : {\n            "query" : "ure",\n            "operator" : "OR",\n            "prefix_length" : 0,\n            "max_expansions" : 50,\n            "fuzzy_transpositions" : true,\n            "lenient" : false,\n            "zero_terms_query" : "NONE",\n            "auto_generate_synonyms_phrase_query" : true,\n            "boost" : 1.0\n          }\n        }\n      },\n      {\n        "match" : {\n          "Proprietary_Source" : {\n            "query" : "ure",\n            "operator" : "OR",\n            "prefix_length" : 0,\n            "max_expansions" : 50,\n            "fuzzy_transpositions" : true,\n            "lenient" : false,\n            "zero_terms_query" : "NONE",\n            "auto_generate_synonyms_phrase_query" : true,\n            "boost" : 1.0\n          }\n        }\n      },\n      {\n        "match" : {\n          "Internal_Comment" : {\n            "query" : "ure",\n            "operator" : "OR",\n            "prefix_length" : 0,\n            "max_expansions" : 50,\n            "fuzzy_transpositions" : true,\n            "lenient" : false,\n            "zero_terms_query" : "NONE",\n            "auto_generate_synonyms_phrase_query" : true,\n            "boost" : 1.0\n          }\n        }\n      }\n    ],\n    "adjust_pure_negative" : true,\n    "boost" : 1.0\n  }\n}')`

my Doc Shema:

```python
from app.models import Funding

from django_elasticsearch_dsl import Document, Index, fields
from django_elasticsearch_dsl.registries import registry

# Name of the Elasticsearch index
INDEX = Index("investors")

INDEX.settings(number_of_shards=1, number_of_replicas=1)


@INDEX.doc_type
class FundingDocument(Document):
    id = fields.IntegerField(attr="id")
    name = fields.TextField(fields={"raw": {"type": "keyword"}})
    organization = fields.TextField(fields={"raw": {"type": "keyword"}})
    Venture_Capital_Investor = fields.TextField(fields={"raw": {"type": "keyword"}})
    Transaction_type = fields.TextField(fields={"raw": {"type": "keyword"}})
    Date = fields.TextField(fields={"raw": {"type": "keyword"}})
    Type = fields.TextField(fields={"raw": {"type": "keyword"}})
    is_lead_investor = fields.TextField(fields={"raw": {"type": "keyword"}})
    Local_Currency = fields.TextField(fields={"raw": {"type": "keyword"}})
    Money_Raised_local = fields.LongField()
    FX_Rate = fields.FloatField()
    Money_Raised_USD = fields.LongField()
    Pre_Money_Valuation = fields.IntegerField()
    Proprietary_Source = fields.TextField(fields={"raw": {"type": "keyword"}})
    Internal_Comment = fields.TextField(fields={"raw": {"type": "keyword"}})

    class Django(object):
        """Inner nested class Django."""

        model = Funding  
```

My view:
```python
from django_elasticsearch_dsl_drf.filter_backends import (
    CompoundSearchFilterBackend,
    FilteringFilterBackend,
)
from django_elasticsearch_dsl_drf.viewsets import DocumentViewSet

from search_indexes.documents import FundingDocument
from search_indexes.serializers import FundingSearchSerializer

from django_elasticsearch_dsl_drf.filter_backends import (
    FilteringFilterBackend,
    IdsFilterBackend,
    OrderingFilterBackend,
    DefaultOrderingFilterBackend,
    SearchFilterBackend,
)

from django_elasticsearch_dsl_drf.constants import (
    LOOKUP_FILTER_TERMS,
    LOOKUP_FILTER_RANGE,
    LOOKUP_FILTER_PREFIX,
    LOOKUP_FILTER_WILDCARD,
    LOOKUP_QUERY_IN,
    LOOKUP_QUERY_GT,
    LOOKUP_QUERY_GTE,
    LOOKUP_QUERY_LT,
    LOOKUP_QUERY_LTE,
    LOOKUP_QUERY_EXCLUDE,
)


class FundingSearchViewSet(DocumentViewSet):
    document = FundingDocument
    serializer_class = FundingSearchSerializer
    lookup_field = 'id'
    filter_backends = [
        FilteringFilterBackend,
        IdsFilterBackend,
        OrderingFilterBackend,
        DefaultOrderingFilterBackend,
        CompoundSearchFilterBackend,
    ]

    search_fields = (
        "name",
        "organization",
        "Venture_Capital_Investor",
        "Transaction_type",
        "Date",
        "Type",
        "is_lead_investor",
        "Local_Currency",
        "Money_Raised_local",
        "FX_Rate",
        "Money_Raised_USD",
        "Pre_Money_Valuation",
        "Proprietary_Source",
        "Internal_Comment",
    )
    # multi_match_search_fields = search_fields
    # Define filter fields
    filter_fields = {
        'id': {
            'field': 'id',
            # Note, that we limit the lookups of id field in this example,
            # to `range`, `in`, `gt`, `gte`, `lt` and `lte` filters.
            'lookups': [
                LOOKUP_FILTER_RANGE,
                LOOKUP_QUERY_IN,
                LOOKUP_QUERY_GT,
                LOOKUP_QUERY_GTE,
                LOOKUP_QUERY_LT,
                LOOKUP_QUERY_LTE,
            ],
        },
        'name': 'name.raw',
        'organization': 'organization.raw',
        'Venture_Capital_Investor': 'Venture_Capital_Investor.raw',
        'Transaction_type': 'Transaction_type.raw',
        'Date': 'Date.raw',
        'Type': 'Type.raw',
        'is_lead_investor': 'is_lead_investor.raw',
        'Local_Currency': 'Local_Currency.raw',
        'Money_Raised_local': {
            'field': 'Money_Raised_local.raw',
            # Note, that we limit the lookups of `price` field in this
            # example, to `range`, `gt`, `gte`, `lt` and `lte` filters.
            'lookups': [
                LOOKUP_FILTER_RANGE,
                LOOKUP_QUERY_GT,
                LOOKUP_QUERY_GTE,
                LOOKUP_QUERY_LT,
                LOOKUP_QUERY_LTE,
            ],
        },
        'FX_Rate': {
            'field': 'FX_Rate.raw',
            # Note, that we limit the lookups of `price` field in this
            # example, to `range`, `gt`, `gte`, `lt` and `lte` filters.
            'lookups': [
                LOOKUP_FILTER_RANGE,
                LOOKUP_QUERY_GT,
                LOOKUP_QUERY_GTE,
                LOOKUP_QUERY_LT,
                LOOKUP_QUERY_LTE,
            ],
        },
        'Money_Raised_USD': {
            'field': 'Money_Raised_USD',
            # Note, that we limit the lookups of `pages` field in this
            # example, to `range`, `gt`, `gte`, `lt` and `lte` filters.
            'lookups': [
                LOOKUP_FILTER_RANGE,
                LOOKUP_QUERY_GT,
                LOOKUP_QUERY_GTE,
                LOOKUP_QUERY_LT,
                LOOKUP_QUERY_LTE,
            ],
        },
        'Pre_Money_Valuation': {
            'field': 'Pre_Money_Valuation',
            # Note, that we limit the lookups of `stock_count` field in
            # this example, to `range`, `gt`, `gte`, `lt` and `lte`
            # filters.
            'lookups': [
                LOOKUP_FILTER_RANGE,
                LOOKUP_QUERY_GT,
                LOOKUP_QUERY_GTE,
                LOOKUP_QUERY_LT,
                LOOKUP_QUERY_LTE,
            ],
        },
    }
    # Define ordering fields
    ordering_fields = {
        'id': 'id',
        'name': 'name.raw',
        'organization': 'organization.raw',
        'Venture_Capital_Investor': 'Venture_Capital_Investor.raw',
        'Transaction_type': 'Transaction_type',
    }
    # Specify default ordering
    ordering = ('id', 'name', 'organization',)
```

My Model:
```python
class Funding(models.Model):
    id = models.IntegerField(db_column="index", primary_key=True)
    name = models.CharField(db_column="name", max_length=105)
    organization = models.CharField(
        db_column="organization_name",
        max_length=105,
    )
    Venture_Capital_Investor = models.CharField(
        db_column="Venture_Capital_Investor",
        max_length=90,
    )
    Transaction_type = models.CharField(
        db_column="Transaction_type",
        max_length=20,
    )
    Date = models.CharField(db_column="Date", max_length=100)
    Type = models.CharField(
        db_column="Type",
        max_length=11,
    )
    is_lead_investor = models.CharField(
        db_column="is_lead_investor",
        max_length=1,
    )
    Local_Currency = models.CharField(
        db_column="Local_Currency",
        max_length=3,
    )
    Money_Raised_local = models.BigIntegerField(
        db_column="Money_Raised_local", default="0"
    )
    FX_Rate = models.DecimalField(
        db_column="FX_Rate", decimal_places=12, max_digits=14, default="0.0"
    )
    Money_Raised_USD = models.BigIntegerField(db_column="Money_Raised_USD", default="0")
    Pre_Money_Valuation = models.IntegerField(
        db_column="Pre-Money_Valuation", default="0"
    )
    Proprietary_Source = models.CharField(
        db_column="Proprietary_Source",
        max_length=260,
    )
    Internal_Comment = models.CharField(
        db_column="Internal_Comment",
        max_length=60,
    )
```

I understand, that this schema have a lot of issues like date is string, bool values as string. I've just started work on this customer's project and it has a lot of issues. Can you help me with looking for a solution for this issue? Maybe incorrect schema   can raise my problem? Thanks

**Comment by barseghyanartur** [comment]
Check the documentation of the [django-elasticsearch-dsl](https://django-elasticsearch-dsl.readthedocs.io/en/latest/fields.html).

This is how you define schema.

```python
@registry.register_document
class CarDocument(Document):
    description = fields.TextField(
        fields={'raw': fields.KeywordField()}
    )

    class Django:
        model = Car
        fields = [
            'name',
            'color',
        ]
```
