### ISSUE TITLE
Do there any blockers to bump new release?

### ISSUE THREAD

**Issue by jramnai** [barseghyanartur/django-elasticsearch-dsl-drf#270]
We are looking forward to using `django-elasticsearch-dsl-drf` with Django 3.2

Required PR is already merged into master branch #263.
Do there any chance a new version will be bumped soon?

If any blockers with the release I would be happy to help.

Thank you in advance.

**Comment by barseghyanartur** [comment]
I'll make one today/tomorrow.

**Comment by barseghyanartur** [comment]
@jramnai:

Done.
