### ISSUE TITLE
Can't sync django database and elasticsearch

### ISSUE THREAD

**Issue by kabrice** [barseghyanartur/django-elasticsearch-dsl-drf#28]
Hi guys,

Great project :)

I am however in a bit of a pickle. Ive setup ElasticSearch, django-elasticsearch-dsl-drf and django-elasticsearch-dsl very well in my project and it mostly seems to work great. Ive tried a lot of things and I am completely stumped so I am hoping someone here might have an idea whats going on :)

Whenever I execute one of those query : 

```
http://localhost:8000/search/books/
http://localhost:8001/search/books/?ids=54|55|56
http://localhost:8001/search/books/?summary__contains=photography
http://localhost:8001/search/books/?tags__contains=ython
http://localhost:8001/search/books/?state=published
http://localhost:8001/search/books/?pages__gt=10&pages__lt=30
```
I get 0 results while my database contains the appropriate data and I've performed:` ./manage.py search_index --create -f` and `./manage.py search_index --populate -f`

Here is my python stack :

```
Django==2.0.1
django-elasticsearch-dsl==0.4.4
django-elasticsearch-dsl-drf==0.6.3
django-nine==0.1.13
django-ormex==0.2
djangorestframework==3.7.7
drf-extensions==0.3.1
elasticsearch==5.5.2
elasticsearch-dsl==5.4.0
factory-boy==2.10.0
Faker==0.8.11
ipaddress==1.0.19
Pillow==5.0.0
psycopg2==2.7.3.2
python-dateutil==2.6.1
pytz==2017.3
PyYAML==3.12
six==1.11.0
text-unidecode==1.1
urllib3==1.22
```

I used a ubuntu 16.0.4 virtualenv with elasticsearch 5.5.3

Thanks for your help

**Comment by barseghyanartur** [comment]
@kabrice 

And you do have data in your database? Are you using example project?

**Comment by kabrice** [comment]
I've data in my database (2 books). My project is from the example project

**Comment by barseghyanartur** [comment]
@kabrice:

Good. 
It's SQLite, right? Could you mail it to me? 
I also need to know what your Elasticsearch version is.

**Comment by kabrice** [comment]
No, I used postgres as database. `./runtests.py` give me a lot of errors like : 
```
src/django_elasticsearch_dsl_drf/tests/test_faceted_search.py:18: in <module>
    import factories
factories/__init__.py:1: in <module>
    from .auth_user import *
factories/auth_user.py:27: in <module>
    class AbstractUserFactory(DjangoModelFactory):
/home/ubuntu/.virtualenvs/book_es/lib/python3.5/site-packages/factory/base.py:91: in __new__
    params=attrs_params,
/home/ubuntu/.virtualenvs/book_es/lib/python3.5/site-packages/factory/base.py:208: in contribute_to_class
    self.model = self.get_model_class()
/home/ubuntu/.virtualenvs/book_es/lib/python3.5/site-packages/factory/django.py:89: in get_model_class
    self.model = get_model(app, model_name)
/home/ubuntu/.virtualenvs/book_es/lib/python3.5/site-packages/factory/django.py:49: in get_model
    return _get_model(app, model)
/home/ubuntu/.virtualenvs/book_es/lib/python3.5/site-packages/django/apps/registry.py:190: in get_model
    self.check_models_ready()
/home/ubuntu/.virtualenvs/book_es/lib/python3.5/site-packages/django/apps/registry.py:132: in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
E   django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

```
Here is a link to my download my project : https://www.dropbox.com/s/cnu3d2eja6bx7u5/book-django.zip?dl=0 

Thank you

**Comment by barseghyanartur** [comment]
@kabrice:

My advice would be:

1. Checkout this repository.
2. Make sure that **this** example project works for you (very easy, ther'e also a management command for creating test data ``books_create_test_data``).
3. If it does (which I assume) try to find out what are the differences between your code and the example project.
