### ISSUE TITLE
boolean query ?

### ISSUE THREAD

**Issue by akhan118** [barseghyanartur/django-elasticsearch-dsl-drf#280]
**Questions**
Hi,

I couldn't find anything on how to do a[ boolean query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html#query-dsl-bool-query). is it possible?

**Comment by barseghyanartur** [comment]
It's a bit tricky question. Most of the queries are boolean. I suggest you to use [django-elasticsearch-debug-toolbar](https://pypi.org/project/django-elasticsearch-debug-toolbar/) or log produced queries to the console in order to get a grasp of what's happening, then come up with a real issue.

**Comment by akhan118** [comment]
I coudln'
