### ISSUE TITLE
How to filter nested with name including underscore

### ISSUE THREAD

**Issue by rsommerard** [barseghyanartur/django-elasticsearch-dsl-drf#281]
I have document with various fields, object fields and nested fields. Some property names include underscore. Here is an example:

```
@registry.register_document
class FooDocument(Document):
    bars = NestedField(
        properties={
            "dead_beef": StringField(),
        }
    )
    ...
```

- How can I filter nested field ?

According to the [documentation](https://django-elasticsearch-dsl-drf.readthedocs.io/en/latest/nested_fields_usage_examples.html#nested-filtering), I tried various way that doesn't work (eg. `http://127.0.0.1:8000/search/foos/?search=bars.dead_beef:Apple`, `http://127.0.0.1:8000/search/foos/?search=bars__dead_beef:Apple`, `http://127.0.0.1:8000/search/foos/?bars.dead_beef=Apple` or `http://127.0.0.1:8000/search/foos/?bars__dead_beef=Apple`)

I don't know if the underscore in the property name is problematic? Is it a way to escape it in query?

**Comment by barseghyanartur** [comment]
I think you have a spelling error (`dead_beef` vs `deed_beef`). Single underscore is no issue.

**Comment by rsommerard** [comment]
I corrected the typo but the issue still remains.

**Comment by rsommerard** [comment]
In the documentation I understand that underscores are converted to points. But in my case It means that attribute `dead_beef` will be converted to `dead.beef` in the query.

![image](https://user-images.githubusercontent.com/8227507/152344470-784765d7-10a2-40b2-935b-6d9675740ccb.png)

**Comment by barseghyanartur** [comment]
@rsommerard:

It's pretty much how you define it in the `ViewSet`. Whatever name you give to that field - would be the name to filter on. And just in case, things are complicated, you could always have some fields indexed double or flat (without nesting) if that's what you need in core.

**Comment by rsommerard** [comment]
> you could always have some fields indexed double or flat (without nesting) if that's what you need in core.

Yep I will go to this solution if it doen't work.

I saw that I forget to add a FilterBackend to my ViewSet, I cannot find what are differrences between `NestedFilteringFilterBackend`, `FilteringFilterBackend` and `SearchFilterBackend`?

**Comment by barseghyanartur** [comment]
Search is slower than filter. Filter can only be done with Keyword fields. Nested is applied to nested fields only.

**Comment by rsommerard** [comment]
Ok I was using `SearchFilterBackend` wich as I understand includes filters.

I declared this in my ViewSet:

```
search_nested_fields = {
        "bars": {
            "path": "bars",
            "fields": ["dead_beef"],
        },
}
```

- What kind of request would you make if you would do this search?

I made this request: `http://127.0.0.1:8000/search/foos/?search=bars.dead_beef:Apple` but I have no result.

**Comment by rsommerard** [comment]
Ok I was using `SearchFilterBackend` wich as I understand includes filters.

I declared this in my ViewSet:

```
search_nested_fields = {
        "bars": {
            "path": "bars",
            "fields": ["dead_beef"],
        },
}
```

- What kind of request would you make if you would do this search?

I made this request: `http://127.0.0.1:8000/search/foos/?search=bars.dead_beef:Apple` but I have no result.

**Comment by barseghyanartur** [comment]
It should be the name you give it: http://127.0.0.1:8000/search/foos/?search=bars:Apple

**Comment by rsommerard** [comment]
Ok I see, if I understand well `bars` in the url is just a key used in search request. It doesn't relate directly in the elastic search.

In other words I could define things like that:

```
search_nested_fields = {
        "joe": {
            "path": "bars",
            "fields": ["dead_beef"],
        },
}
```

and request with: `http://127.0.0.1:8000/search/foos/?search=joe:Apple`
Doing this will result the same?

**Comment by barseghyanartur** [comment]
Yep.

**Comment by rsommerard** [comment]
I have another issue with the filtering notion.

What I want is to get all result of a certain type. Imagine having a `type` attribute defining a type of juice. It can be `Orange juice` or `Tomato juice`. I want to make a search on `Orange` juice only.

I  import and use `NestedFilteringFilterBackend` in my ViewSet, setted variables like this:

```
nested_filter_fields = {
        "juice_filter": {
            "field": "juice_type.raw",
            "path": "juice",
        }
    }
```

in document, like you said I use a `KeywordField()`:

```
juice = NestedField(
    properties={
         "juice_type": StringField(
             fields={
                 "raw": KeywordField(),
             },
          ),
    }
)
```

Request made: `http://localhost:8000/search/foos/?juice_filter=Orange%20juice`.

I tried different `path` in `nested_filter_fields` but the requests doesn't return anything.

Can you see what is wrong in my approach?

**Comment by barseghyanartur** [comment]
It should be like this:

```python
nested_filter_fields = {
        "juice_filter": {
            "field": "juice.juice_type.raw",
            "path": "juice",
        }
    }
```

**Comment by barseghyanartur** [comment]
`NestedFilteringFilterBackend` should be enough for this. I suggest to log all Elastic queries into console and trying to understand whether filters are applied or not. 

Alternatively, you could always simplify things and index a separate non-nested keyword field in the document.

**Comment by rsommerard** [comment]
OK, thanks a lot for your time. Your answers helped me a lot!
