### ISSUE TITLE
Does this package works with Elasticsearch 7.7 running in AWS->Opensearch?

### ISSUE THREAD

**Issue by sg3847** [barseghyanartur/django-elasticsearch-dsl-drf#287]
Hi,

I installed ```django-elasticsearch-dsl-drf==0.22.4``` (latest version) in my Django project and it installed successfully along with the dependencies. I'm using this package to connect to ElasticSearch 7.7 instance running in AWS->OpenSearch. However, while connecting to the Opensearch cluster, I'm getting this error: 
```elasticsearch.exceptions.UnsupportedProductError: The client noticed that the server is not a supported distribution of Elasticsearch```
I'm also using ```Django==4.0.2``` and I'm not sure if this package is compatible with Django==4.0.2. Can you please confirm if the latest version of this package would work in my current Django/ElasticSearch environment?

Thanks.

**Comment by barseghyanartur** [comment]
@sg3847

It is possible to make it working, however, I'm adding a full compatibility with `django-opensearch-dsl` package (which delivers first class support for `opensearch-dsl` package) one of these days.

**Comment by barseghyanartur** [comment]
[WIP](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/tree/feature/support-both-opensearch-and-elasticsearch).

**Comment by Ameer-Amr** [comment]
> [WIP](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/tree/feature/support-both-opensearch-and-elasticsearch).

Hi, @barseghyanartur Is this feature available now? if yes, could you please share the doc/example of the same?

**Comment by barseghyanartur** [comment]
> Hi, @barseghyanartur Is this feature available now? if yes, could you please share the doc/example of the same?

If it would, it wouldn't be WIP and this ticket would be closed. :)

**Comment by barseghyanartur** [comment]
As of now, my local tests (except one which is kind of irrelevant) are passing with both Elasticsearch 7.x and OpenSearch 2.x. Please, check the [feature branch](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/tree/feature/support-both-opensearch-and-elasticsearch) and leet me know you have faced any issues,

**Comment by barseghyanartur** [comment]
@sg3847 
@Ameer-Amr

**Comment by barseghyanartur** [comment]
BTW, as of rhis ticket exactly, I've recently used this package with AWS Elasticsearch service (Elasticsearch version 7.10). It worked just fine. OpenSearch support is discussed in a separate thread.
