### ISSUE TITLE
Can I obtain all id's and process them in DocumentViewSet?

### ISSUE THREAD

**Issue by michalpulpan** [barseghyanartur/django-elasticsearch-dsl-drf#288]
**Questions**

Hello, 

First of all, thank you for a very good library.
`DocumentViewSet` currently works in a way that it (well, pretty much) returns directly result obtained from ElasticSearch. 

Is it possible to get ElasticSearch's response (primairly just object id's) and do some business logic inside of `DocumentViewSet`?
I went through the docs and didn't find anything really helpful for this problem.

I'm aware of loosing performance gains but this use-case isn't suppose to work instantly, I mainly need to obtain list of objects retrieved from elastic for a given query.

Thanks a lot.

**Comment by barseghyanartur** [comment]
Sure.

You have `get_queryset` and `get_object` where you can do pretty much (with request, if your query is supposed to be limited for certain users) and you can have custom serializers. Do you need more? If so, please describe what exactly.

**Comment by barseghyanartur** [comment]
Closed to to inactivity.
