### ISSUE TITLE
LimitOffsetPagination count behavior

### ISSUE THREAD

**Issue by boolangery** [barseghyanartur/django-elasticsearch-dsl-drf#294]
Hello,

If you look a the snippet bellow from LimitOffsetPagination:

https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/a5d195fa7a20f87207855955bc5176b89081abdb/src/django_elasticsearch_dsl_drf/pagination.py#L376-L382

We can see that the count id done after slicing the query set.  So its not a total document count. Is this the intended behavior. (Note in Drf LimitOffsetPagination the count is done before)

Thanks

**Comment by barseghyanartur** [comment]
Did you actually test it? :) Please, try. If there are issues with the count, I'd love to fix them (but you won't find any). :)

**Comment by boolangery** [comment]
Yes I tested it but it was the max_result_window :x
