### ISSUE TITLE
Standard analyzer is not applied by default

### ISSUE THREAD

**Issue by spotamushroom** [barseghyanartur/django-elasticsearch-dsl-drf#297]
**Describe the bug**
When no analyzer is defined, I would expect the default analyzer to be applied:
"tokenizer": "standard","filter": [ "lowercase", "stop" ].

**Environment**

Python environment:
1. `pip list`
2. `python --version`
Package                      Version
---------------------------- -----------
asgiref                      3.5.2
beautifulsoup4               4.11.1
biopython                    1.79
bleach                       5.0.1
certifi                      2022.6.15
chardet                      5.0.0
charset-normalizer           2.1.0
Django                       3.2
django-bootstrap3            21.2
django-contrib-comments      2.2.0
django-elasticsearch-dsl     7.2.2
django-elasticsearch-dsl-drf 0.22.5
django-filter                22.1
django-nine                  0.2.5
django-tables2               2.4.1
djangorestframework          3.13.1
elasticsearch                7.17.4
elasticsearch-dsl            7.4.0
filebrowser-safe             1.1.1
grappelli-safe               1.1.1
idna                         3.3
Mezzanine                    6.0.0
mssql-django                 1.1.3
numpy                        1.23.1
oauthlib                     3.2.0
Pillow                       9.2.0
pip                          22.2.1
psycopg2                     2.9.3
pyodbc                       4.0.34
python-dateutil              2.8.2
pytz                         2022.1
pytz-deprecation-shim        0.1.0.post0
requests                     2.28.1
requests-oauthlib            1.3.1
setuptools                   57.4.0
six                          1.16.0
soupsieve                    2.3.2.post1
sqlparse                     0.4.2
tinycss2                     1.1.1
tzdata                       2022.1
tzlocal                      4.2
urllib3                      1.26.11
webencodings                 0.5.1
xlwt                         1.3.0

Python 3.9.7

Which version of Elasticsearch are you using?
7.17.5

**To Reproduce**
1. Define field with no analyzer, e.g. `    target = fields.TextField(
        fields={
            'raw': fields.TextField(analyzer='keyword'),
        }
    )`
2. `TargetStatusDocument.search().query('match', target='12797.a').count() = 13795 # expected = 16`
3. Include explicit default analyzer: 
```
should_be_default_but_isnt = analyzer(
    'should_be_default_but_isnt',
    tokenizer="standard",
    filter=["lowercase", "stop"]
)

target = fields.TextField(
        analyzer=should_be_default_but_isnt,
        fields={
            'raw': fields.TextField(analyzer='keyword'),
        }
    )
```
4. `TargetStatusDocument.search().query('match', target='12797.a').count() = 16 # OK`

**Expected behavior**
When no analyzer is specified in the field definition, I would expect the default analyzer to be applied:
`"tokenizer": "standard","filter": [ "lowercase", "stop" ].`

**Comment by barseghyanartur** [comment]
This is irrelevant for this project, since Search Index Documents are defined using ``django-elasticsearch-dsl``. Also, instead of using ``fields.TextField(analyzer="keyword")`` you should better use ``fields.KeywordField()``.
