### ISSUE TITLE
how to search any query in multiple or all indexes or multiple documents?

### ISSUE THREAD

**Issue by anirbanchakraborty123** [barseghyanartur/django-elasticsearch-dsl-drf#299]
**Questions**

How to search any query in multiple indexes or multiple documents using elasticsearch-dsl-drf.

**Comment by barseghyanartur** [comment]
Not out-of-the-box possible, but I've done that. It is, however, very much dependent on your use-case (which falls out of the scope of this project). Contact me (see the readme) for more information.
