### ISSUE TITLE
Add `coreapi` and `coreschema` integration

### ISSUE THREAD

**Issue by barseghyanartur** [barseghyanartur/django-elasticsearch-dsl-drf#30]
Add `coreapi` and `coreschema` integration.

**Comment by macher91** [comment]
Please check https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/pull/34

**Comment by barseghyanartur** [comment]
@macher91:

Thanks a lot! I have merged into a [coreapi-and-coreschema-support](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/tree/coreapi-and-coreschema-support) branch.

Could you add some tests covering the addition of `coreapi` and `coreschema`?

**Comment by macher91** [comment]
@barseghyanartur tests has been added

**Comment by barseghyanartur** [comment]
@macher91:

Test requirements shall be updated too (missing `coreapi` and `coreschema` packages). 
Could you make an update?

**Comment by macher91** [comment]
@barseghyanartur test requirements has been updated.

**Comment by barseghyanartur** [comment]
@macher91:

Thanks for your contributions!

**Comment by barseghyanartur** [comment]
@macher91:

Released in 0.7.
