### ISSUE TITLE
How to use ignore_above in below case ?

### ISSUE THREAD

**Issue by BharatSth** [barseghyanartur/django-elasticsearch-dsl-drf#304]
![error](https://user-images.githubusercontent.com/107904448/207014177-29d7c2d3-fc29-4751-8a8b-69e1c5648793.png)

**Comment by Animeshshrestha** [comment]
How to set index=False for Nested (). Currently  it  returns 'Mapping definition for [mydocument] has unsupported parameters: [index=False] for nested Field()
