### ISSUE TITLE
The usage of | in queries is ambiguous

### ISSUE THREAD

**Issue by rrmerugu** [barseghyanartur/django-elasticsearch-dsl-drf#32]
This is an enhancement suggestion. In https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/basic_usage_examples.rst 

In the example query `http://127.0.0.1:8080/search/publisher/?city__in=yerevan|amsterdam` I was thinking `http://127.0.0.1:8080/search/publisher/?city__in=yerevan,amsterdam` feels more readable to me ! do you see any conflicts if we use " , " instead of | .

In the example `http://127.0.0.1:8080/search/publisher/?search=name|reilly&search=city|london` how about `http://127.0.0.1:8080/search/publisher/?search=name:reilly&search=city:london` I'm not familiar in elasticsearch, but in solr we use `field:value` patterns in search, Im assuming that syntax would be more user friendly and already established syntax.

context of pipe in both the places feels bit confusing for me. If you think we can change that without breaking any features. I can pitch-in to fix that .

UPDATE:
I can see comma as a seperator doesn't work in this scenario `http://localhost:8000/search/publishers/?location__geo_polygon=40,-70|30,-80|20,-90`

**Comment by barseghyanartur** [comment]
@rrmerugu:

The main reason of using the pipe `|` instead of comma `,` is that pipe is seldom used in texts, titles, while usage of comma is quite common.

Thus, I'd say, leave it as it is.

**Comment by rrmerugu** [comment]
sounds good.
