### ISSUE TITLE
search_index command not working 

### ISSUE THREAD

**Issue by siddharthk-hashedin** [barseghyanartur/django-elasticsearch-dsl-drf#43]
I have gone through the documentation and was implementing django-elasticsearch-dsl-drf on my project.
I have created documents but 
./manage.py search_index command is not working.
 It's showing 
"""""""""""""
Unknown command: 'search_index'
Type 'manage.py help' for usage.
""""""""""""
in output console. 
PS: I have already installed rest framework, elasticsearch-dsl and django-elasticsearch-dsl-drf

**Comment by barseghyanartur** [comment]
Add django_elasticsearch_dsl and django_elasticsearch_dsl_drf to your installed apps.

**Comment by siddharthk-hashedin** [comment]
I have already added them.

**Comment by barseghyanartur** [comment]
Did you install django-elasticsearch-dsl?

**Comment by siddharthk-hashedin** [comment]
A part of my pip freeze inside my virtual environment is:

```
Django==1.10.4
django-elasticsearch-dsl==0.4.4
django-elasticsearch-dsl-drf==0.7.1
```

**Comment by barseghyanartur** [comment]
Something is wrong with your settings. If you have installed reqs and added both apps mentioned above to your installed apps, it should work. Try to clone this repo locally and run same commands from example app.

**Comment by siddharthk-hashedin** [comment]
It worked after lot of configurations changes.
I have not created separate application for search_indexes instead put all documents specific conf in a module of app how to specify search_index to take DocType specified in that module?

**Comment by siddharthk-hashedin** [comment]
Also how to verify if create and populate search_index has been done properly

**Comment by barseghyanartur** [comment]
It's explained in docs, as a recemmendation. Sorry, I can't tell you mote at the moment.

**Comment by siddharthk-hashedin** [comment]
Okay, last thing when i ran search_index create command it doesn't show any out put on screen.

**Comment by barseghyanartur** [comment]
You should run update as well.

**Comment by barseghyanartur** [comment]
Read about indexes here

http://django-elasticsearch-dsl-drf.readthedocs.io/en/0.7.1/quick_start.html#syncing-django-s-database-with-elasticsearch-indexes

**Comment by barseghyanartur** [comment]
I'm closing this for now, as I understand it's a matter of a proper configuration. Feel free to post updates and open new issues.

**Comment by hipertracker** [comment]
I have the same problem. search_index  does not exist. It would be good to add a minimalistic full working code example to docs. The current example is too big, it contains a lot of models.

**Comment by siddharth-kulshrestha** [comment]
Hi @hipertracker ,
Also as mentioned above thing that worked for me 2 years before was refactoring and changing directories according to what mentioned in the settings.

One of my mate has recently implemented one of the examples mentioned in this repo. 
You can have a look at it here. 

https://github.com/apankit2490-hashedin/django-elasticsearch

**Comment by hipertracker** [comment]
@siddharth-kulshrestha  are you sure is it the correct class to define the associated model? Should not it be the inner Django class?

```python
class Meta(object): # <-- Django??
    """Inner nested class Django."""
    model = Book  # The model associate with this Document
```

**Comment by barseghyanartur** [comment]
Docs need to be slightly updated.

Pick any of the existing examples. They all work (tests are based on them).

**Comment by siddharth-kulshrestha** [comment]
@hipertracker Yes it should be an inner django class.

check [this](https://github.com/apankit2490-hashedin/django-elasticsearch/blob/908d22fad08bc64e7b82cc799b9f15b4f507b646/dj_es_books/search_indexes/documents/book.py#L95)

**Comment by barseghyanartur** [comment]
Guys, there's an [open issue](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/issues/73). Help is appreciated.
