### ISSUE TITLE
search_index with create, populate and rebuild does'nt show any output on screen

### ISSUE THREAD

**Issue by siddharthk-hashedin** [barseghyanartur/django-elasticsearch-dsl-drf#44]
After building document I am running 
python manage.py search_index --create -f 
python manage.py search_index --populate -f
python manage.py search_index --rebuild -f

commands but it is not showing any output on screen commands simply runs and exits from command and doesn't shows any output on screen. Beside rebuild only shows an output for choosing yes or no.
IT SHOWS : 
Are you sure you want to delete the '' indexes?  [n/Y]:

I am using,
certifi==2018.1.18
chardet==3.0.4
coreapi==2.3.3
coreschema==0.0.4
coverage==4.4.1
dj-database-url==0.4.2
dj-email-url==0.0.10
Django==1.11.1
django-coverage-plugin==1.4.2
django-elasticsearch-dsl==0.4.4
django-elasticsearch-dsl-drf==0.7.1
django-filter==1.0.2
django-nine==0.1.13
django-rest-swagger==2.1.2
djangorestframework==3.6.3
elasticsearch==5.5.2
elasticsearch-dsl==5.1.0
gunicorn==19.7.1
idna==2.6
ipaddress==1.0.21
itypes==1.1.0
Jinja2==2.10
Logentries==0.17
MarkupSafe==1.0
openapi-codec==1.3.2
python-dateutil==2.7.2
pytz==2018.4
requests==2.18.4
simplejson==3.13.2
six==1.11.0
uritemplate==3.0.0
urllib3==1.22
whitenoise==3.3.0

these versions also i have turned on elasticsearch 5.5.2 server on localhost 9200 and added these configs in my settings.py.
Help me if you have any idea why am I facing this issue.
![screenshot from 2018-04-15 21-59-47](https://user-images.githubusercontent.com/36027643/38780711-8da62f4c-40f8-11e8-9757-66bd49443d2c.png)

**Comment by barseghyanartur** [comment]
Just rebuild would be sufficient.

```sh
python manage.py search_index --rebuild -f
```

You don't need to run all 3.

Did you configure indexes properly? Does "example" project work for you? I would advice to study the docs (of this package) well first. Especially the indexes part (of the quick start).
