### ISSUE TITLE
multi_match with type= phrase_prefix, And Date() type is showing date with timestamps.

### ISSUE THREAD

**Issue by siddharthk-hashedin** [barseghyanartur/django-elasticsearch-dsl-drf#47]
How to implement "multi_match" query with phrase_prefix type.
I want to implement search for keywords.
Also,
let me know how to handle date? 
While creating Date field i am also getting timestamp.

**Comment by barseghyanartur** [comment]
@siddharthk-hashedin:

Have you studied the documentation?

If supported filters and queries aren't enough, you better make your own search/filter filter backend.

You can format your date using Django or Python.
