### ISSUE TITLE
Transaction support

### ISSUE THREAD

**Issue by kabrice** [barseghyanartur/django-elasticsearch-dsl-drf#48]
I just setup transaction within my Django view. I just noticed that every time there is a `rollback`, the data is save and sync through Elasticsearch while `unsave` on my database. 
How can I apply transaction in this package ?

**Comment by barseghyanartur** [comment]
@kabrice:

This is out of the scope of this package. You better ask your question [here](https://github.com/sabricot/django-elasticsearch-dsl).
