### ISSUE TITLE
Count never change when using pagination

### ISSUE THREAD

**Issue by kabrice** [barseghyanartur/django-elasticsearch-dsl-drf#49]
When I use pagination through `pagination_class = LimitOffsetPagination`, it works very well, but the count value never change. For example if `http://127.0.0.1:8000/search/books/` returns 10 results, count will be 10 and then if I use `http://127.0.0.1:8000/search/books/?limit=1`, it will return  only `one result` but count doesn't change at all, we still have `count=10`.
Is is normal ?

**Comment by barseghyanartur** [comment]
@kabrice:

At the moment count represents the amount of records per page.
