### ISSUE TITLE
Can I change the structure if the requested url structure

### ISSUE THREAD

**Issue by Fettah** [barseghyanartur/django-elasticsearch-dsl-drf#75]
When requesting the API, i have to use some already defined url structure like: `color__terms=1__2` or `id__in=1__2`. I have already a front end application that uses a certain structure. something like : `?id=1,2& meterial=1,2`, and changing the front end application is quit complex. Is there a way to handle this with `django-elasticsearch-dsl-drf`.

**Comment by barseghyanartur** [comment]
@Fettah:

Short answer for that would be no. However, for such cases, you can simply use arrays.

So, instead of:

```
?color__terms=1__2
```

you would write:

```
?color=1&color=2
```

Same goes for material.

**Comment by Fettah** [comment]
@barseghyanartur 
I am looking for more for `?color=1,2`. we had a search/filter implemented this way, and we want to upgrade with minimum effort possible

**Comment by barseghyanartur** [comment]
@Fettah:

Unfortunately not. And actually, it was never comma (`,`) separated. In some cases pipe (`|`) was used, but I got rid of that in favour of double underscores so that complex query backends, such as `simple_query_string` (and in future - `query_string`) could be implemented.
