### ISSUE TITLE
How to use 'logging' to log a search GET request into logfile?

### ISSUE THREAD

**Issue by JasonHXiang** [barseghyanartur/django-elasticsearch-dsl-drf#77]
Hi~ 
I want to use Python module 'logging' to log the search details. For example, someone sends a GET request to get several resources in the Elasticsearch, then I want to log like this

`ERROR 2018-08-23 16:35:35,492  User-Tommy	  GET	/search/topics/  {"ordering": "-id", "creator": 3}`

so, what should I do?

**Comment by barseghyanartur** [comment]
@JasonHXiang:

Google for `logging elasticsearch-py`, since that's what we using.

**Comment by JasonHXiang** [comment]
@barseghyanartur 
Thanks for replying for my question 😄
By the way, another question comes. Where should I add the logger 'elasticsearch.trace' to take effect? In the _documents_, _viewsets_ or _serializers_?

**Comment by barseghyanartur** [comment]
@JasonHXiang:

I think documents would be the right place, since they are loaded in any case.

**Comment by JasonHXiang** [comment]
@barseghyanartur :
OK, I'll have a try.
If I want to access the _'self.request'_  in the search_indexes app, for example in the documents, viewsets or serializers, how would I place the 'self.request' in the files?

**Comment by barseghyanartur** [comment]
@JasonHXiang:

It shouldn't be possible to access `self.request` in documents, but as for viewsets and serializers - it's quite common in Django REST Framework. Google for it or search StackOverflow.
