### ISSUE TITLE
BaseDocumentViewSet ignores the "using" Meta variable

### ISSUE THREAD

**Issue by SimKennedy** [barseghyanartur/django-elasticsearch-dsl-drf#78]
The BaseDocumentViewSet will only use the "default" connection set in ELASTICSEARCH_DSL settings, even if "using" is set in the django_elasticsearch_dsl document "Meta" var.

    class Meta:
        doc_type = "doctype_name"
        using = "connectionAlias"
        model = MyModel

https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/5ccbb108f9ab7bda4fa5a6f41aab83e191282ed4/src/django_elasticsearch_dsl_drf/viewsets.py#L157

I think just this change is needed to use the "using" variable if it is given, else use "default" if not.

self.client = connections.get_connection()
to
self.client = connections.get_connection(self.document._doc_type.using)

**Comment by barseghyanartur** [comment]
@SimKennedy:

Good point. I'll fix it one day soon. 

You're also welcome to make a pull request. Docs and tests shall be updated accordingly.

**Comment by barseghyanartur** [comment]
Solved in 0.16.
