### ISSUE TITLE
Case Insensitive search

### ISSUE THREAD

**Issue by Fettah** [barseghyanartur/django-elasticsearch-dsl-drf#79]
hi, 
I need some help here.
by using  a config like this:

```
filter_backends = [
        SearchFilterBackend,
    ]

    search_fields = (
        'brand',
        'categories',
    )

    search_nested_fields = {
        'brand': ['name'],
        'categories': ['name'],
    }

```

I noticed that the search is case sensitive. How do I overcome that ? I want ES to ignore the case.
sending: Amazon and amazon should give the same result

**Comment by barseghyanartur** [comment]
@Fettah:

Please, search before asking again.

https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/issues/53
