### ISSUE TITLE
Duplicated function get_geo_distance_params

### ISSUE THREAD

**Issue by id13** [barseghyanartur/django-elasticsearch-dsl-drf#8]
https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/6842437ad3618db692f491e067114ea4ad52ffda/src/django_elasticsearch_dsl_drf/filter_backends/filtering/common.py#L164

Present in both `filtering/common` and `filtering/geo_spatial`

#4

**Comment by barseghyanartur** [comment]
@id13:

Thanks! Done.
