### ISSUE TITLE
Facet aggregation return only 10 result

### ISSUE THREAD

**Issue by temi4** [barseghyanartur/django-elasticsearch-dsl-drf#80]
Hello 

Do facet aggregation:
http://take.ms/jHIom
Return only 10 result. 
How I may return  all result? 

Need add size=0 params to facet query
How I may do this? 
https://stackoverflow.com/questions/47219846/elasticsearch-dsl-aggregations-returns-only-10-results-how-to-change-this

**Comment by temi4** [comment]
resolve

'letter': {
            'field': 'letter',
            'facet': TermsFacet,
            'options':{
                'size': 9999,
            }
        }

**Comment by barseghyanartur** [comment]
@temi4:

Yep. That's exactly how you should do it.
