### ISSUE TITLE
page_size_query_param is not set in PageNumberPagination so the pagination doesn't work

### ISSUE THREAD

**Issue by atadych** [barseghyanartur/django-elasticsearch-dsl-drf#81]
Because `page_size_query_param` is not set in `rest_framework.pagination.PageNumberPagination` (default value is `None`) so pagination using `django_elasticsearch_dsl_drf.pagination.PageNumberPagination` doesn’t work.

According to [rest_framework](https://github.com/encode/django-rest-framework/blob/master/rest_framework/pagination.py), the client should define the value for param `page_size_query_param` (e.g “page_size”) to enable usage.

```
class PageNumberPagination(BasePagination):
….

    # Client can control the page size using this query parameter.
    # Default is 'None'. Set to eg 'page_size' to enable usage.
    page_size_query_param = None
    page_size_query_description = _('Number of results to return per page.')
```

This param is not set, so in `PageNumberPagination(pagination.PageNumberPagination)` 
the line below (LN141) always returns `None`

`page_size = self.get_page_size(request)`

It works after initializing `page_size_query_param` with "page_size".
```
    def __init__(self, *args, **kwargs):
        """Constructor.

        :param args:
        :param kwargs:
        """
        self.facets = None
        # self.page = None
        # self.request = None

        self.page_size_query_param='page_size'
        self.count = None
        super(PageNumberPagination, self).__init__(*args, **kwargs)
```

**Comment by barseghyanartur** [comment]
@atadych:

That's solely problem of Django REST framework.

**Comment by atadych** [comment]
But your `PageNumberPagination` inherits from their class....

According to the [documentation](https://django-elasticsearch-dsl-drf.readthedocs.io/en/0.16/advanced_usage_examples.html?#pagination) pagination should work by default (with `PageNumberPagination`) but it didn't work for me.
When I changed the pagination class to `LimitOffsetPagination` class then it started working..

Nevertheless I spent some time looking why the default `PageNumberPagination` doesn't work and then I saw this comment in Django REST framework.

**Comment by barseghyanartur** [comment]
@atadych:

The most logical solution would be on the side of Django REST framework. I wonder, why there's no such setting as ``PAGE_SIZE_QUERY_PARAM``.

However, it might be worth to document that [here](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/docs_src/advanced_usage_examples.rst#pagination) as well.

**Comment by atadych** [comment]
Ok, finally I got why it didn't work for me with default pagination.
I didn't set `PAGE_SIZE` in `REST_FRAMEWORK` settings, so by default the pagination was disabled.

Mentioning this in your [docs](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/docs_src/advanced_usage_examples.rst#pagination) could be helpful for others.

Thanks for your work!

**Comment by renatogp** [comment]
For those having the same issue, change `pagination_class` from `PageNumberPagination` to `QueryFriendlyPageNumberPagination`. This will enable`?page_size=X`.
