### ISSUE TITLE
How to specify a size of results for functional suggester?

### ISSUE THREAD

**Issue by atadych** [barseghyanartur/django-elasticsearch-dsl-drf#83]
I have defined a functional suggester.
``` 
#documents
all_names = StringField(
        attr='all_names',
        fields={
            'edge_ngram_completion': StringField(
                analyzer=edge_ngram_completion_analyzer3_20,
                search_analyzer=whitespace_lowercase_analyzer
            ),

        }
    )


#viewsets.py
```        'all_names': {
            'field': 'all_names.edge_ngram_completion',
            'suggesters': [FUNCTIONAL_SUGGESTER_COMPLETION_MATCH],
            'default_suggester': FUNCTIONAL_SUGGESTER_COMPLETION_MATCH,
        },
```

The query works fine (underlying ES query looks like this):
``` {
  "query": {
    "match": {
      "all_names.edge_ngram_completion": "mpr"
    }
  },
  "sort": [
    "_score"
  ]
}
```
However (by default) there are max 10 results returned. How can I can control this number (define the size for the query)? I was trying to add options to fields but wasn't sure where to put it exactly.

When querying ES directly, I can control that...
``` {
  "query": {
    "match": {
      "all_names.edge_ngram_completion": "mpr"
    }
  },
 "size":25,
  "sort": [
    "_score"
  ]
}
```

Thanks

**Comment by barseghyanartur** [comment]
@atadych:

Good question. I think at the moment number of results of the functional suggester is limited by the ``PAGE_SIZE`` param of the Django REST framework configuration. In my use cases, ``PAGE_SIZE`` was usually 100 or 200, thus, tweaking the Elastic ``size`` param was not necessary. However, in case of small values (like in your case - 10), it might be useful to be able to override it on the functional suggester level. I'll add it to the list of TODOs.

In the meantime, you could:

- Increase the ``PAGE_SIZE`` param (to 50 for example).
- Define ``page_size_query_param`` (if I'm not mistaken, it shall be done on Paginator level; check in details in the Django REST framework) .
- Whenever you need to have less results, provide ``page_size_query_param`` (that's how I think it's called within Django REST framework) in the query string.

**Comment by atadych** [comment]
But does pagination work for functional suggester?
Line 135 in [pagination.py](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/src/django_elasticsearch_dsl_drf/pagination.py)
```
  def paginate_queryset(self, queryset, request, view=None):

       ...

        # Check if we're using paginate queryset from `functional_suggest`
        # backend.
        if view.action == 'functional_suggest':
            return queryset
```

**Comment by barseghyanartur** [comment]
@atadych:

Did you try to increase the ``PAGE_SIZE`` param to 50 and checked if number of records returned by functional suggester went up?

**Comment by atadych** [comment]
Yes, I changed that to 4, here is the ES query for getting all objects (pagination works):
```
{
  "from": 0,
  "query": {
    "match_all": {}
  },
  "size": 4,
  "sort": [
    "_score",
    "entrez",
    "symbol"
  ]
}
```

And here is functional suggester query, still without size
```

  "query": {
    "match": {
      "all_names.edge_ngram_completion": "mra"
    }
  },
  "sort": [
    "_score"
  ]
}
```

**Comment by barseghyanartur** [comment]
@atadych:

Oops. Sorry for inconvenience. It indeed has nothing to do with page size param.

I've added an option to control that in version 0.16.1.

```python
# Functional suggester fields
        functional_suggester_fields = {
            'title_suggest': {
                'field': 'title.raw',
                'suggesters': [
                    FUNCTIONAL_SUGGESTER_COMPLETION_PREFIX,
                ],
                'default_suggester': FUNCTIONAL_SUGGESTER_COMPLETION_PREFIX,
                'options': {
                    'size': 25,
                    'from': 0,
                }
            },
            'title_suggest_match': {
                'field': 'title.edge_ngram_completion',
                'suggesters': [FUNCTIONAL_SUGGESTER_COMPLETION_MATCH],
                'default_suggester': FUNCTIONAL_SUGGESTER_COMPLETION_MATCH,
            }
        }
```

**Comment by atadych** [comment]
Thanks, it works now with new version.
