### ISSUE TITLE
Query string with colon for multi match search

### ISSUE THREAD

**Issue by atadych** [barseghyanartur/django-elasticsearch-dsl-drf#84]
Hi,
I am using MultiMatchSearchFilterBackend and when searching for example for `ataxia`
(`GET /search/diseases/?search_multi_match=ataxia`)
this will result in this query
```
{
  "query": {
    "bool": {
      "must": [
        {
          "multi_match": {
            "fields": [
              "all_names.edge_ngram_completion",
              "doid.edge_ngram_completion^2"
            ],
            "query": "ataxia"
          }
        }
      ]
    }
  },
}
```
and the results will be like this
```
 "results": [
        {
            "id": 1622,
            "doid": "DOID:12704",
            "name": "ataxia telangiectasia"
        },
        {
            "id": 6146,
            "doid": "DOID:963",
            "name": "episodic ataxia"
        },
      ...
]
```

However because my `doid` field contains colon, I can also have query like this
`GET /search/diseases/?search_multi_match=DOID:006`

It looks like `MultiMatchSearchFilterBackend` treats colon as a special character to find and split the field names so as the result the underlying query is incorrect.
```
{
  "query": {
    "bool": {
      "must": [
        {
          "multi_match": {
            "fields": [],
            "query": "006"
          }
        }
      ]
    }
  },
}
```
Is there any way to use colon in the query string?

**Comment by barseghyanartur** [comment]
@atadych:

Short answer would be no.

However:

- You could override the ``MultiMatchSearchFilterBackend`` backend and take away the ``:`` functionality.
- You could remove ``DOID:`` parts from your strings and search for numbers.

**Comment by atadych** [comment]
Ok, got it! I think I will override `MultiMatchQueryBackend` to ignore colon
