### ISSUE TITLE
Wrong import in docs

### ISSUE THREAD

**Issue by PetrDlouhy** [barseghyanartur/django-elasticsearch-dsl-drf#93]
In quick start section of the docs (https://django-elasticsearch-dsl-drf.readthedocs.io/en/0.16.3/quick_start.html#id4) is mentioned import of `BaseDocumentViewSet`, which should be:
```
from django_elasticsearch_dsl_drf.viewsets import BaseDocumentViewSet
```
rather than
```
from django_elasticsearch_dsl_drf.views import BaseDocumentViewSet
```

**Comment by barseghyanartur** [comment]
I think it's already fixed in the source code, but didn't yet appear in the release. Thanks anyway.
