### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by infokani** [barseghyanartur/django-elasticsearch-dsl-drf#97]
Removing intermediate container b3e80f8db509
 ---> 090de6c962a4
Successfully built 090de6c962a4
Successfully tagged django_elasticsearch_dsl_drf_frontend:latest
Recreating 371176f45073_elasticsearch ... error

ERROR: for 371176f45073_elasticsearch  Cannot start service elasticsearch: driver failed programming external connectivity on endpoint elasticsearch (5600fe32891c41e6393d7ef4849c131b287304c6c60d00687f3d0589cbc1c12d): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:9300:tcp:172.18.0.2:9300: input/output error

ERROR: for elasticsearch  Cannot start service elasticsearch: driver failed programming external connectivity on endpoint elasticsearch (5600fe32891c41e6393d7ef4849c131b287304c6c60d00687f3d0589cbc1c12d): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:9300:tcp:172.18.0.2:9300: input/output error
ERROR: Encountered errors while bringing up the project.

**Comment by barseghyanartur** [comment]
@infokani:

Thanks for reporting this. I'll check it.

**Comment by infokani** [comment]
i think that error was mine and had another problem. I will create another issue.
