### ISSUE TITLE
After docker build only Elastic up Back and Front down

### ISSUE THREAD

**Issue by infokani** [barseghyanartur/django-elasticsearch-dsl-drf#98]
> Windows 10

Building elasticsearch
Step 1/5 : FROM docker.elastic.co/elasticsearch/elasticsearch:6.3.2
 ---> 329273f35ab4
Step 2/5 : ADD ./docker/elasticsearch/elasticsearch.yml /usr/share/elasticsearch/config/
 ---> 77d9dffbb726
Step 3/5 : USER root
 ---> Running in 45f4ed5d4d29
Removing intermediate container 45f4ed5d4d29
 ---> 07dd447f9d00
Step 4/5 : RUN chown elasticsearch:elasticsearch config/elasticsearch.yml
 ---> Running in ebd4d7274704
Removing intermediate container ebd4d7274704
 ---> 75dca86c594b
Step 5/5 : USER elasticsearch
 ---> Running in 92aeb0086900
Removing intermediate container 92aeb0086900
 ---> d7000326c7f1
Successfully built d7000326c7f1
Successfully tagged docker.elastic.co/elasticsearch/elasticsearch:6.3.2
Building backend
Step 1/19 : FROM python:3.6.7-slim-jessie
 ---> 3022fa163c3e
Step 2/19 : ENV PYTHONUNBUFFERED 1
 ---> Using cache
 ---> a434579d781f
Step 3/19 : RUN apt-get update
 ---> Using cache
 ---> ac7907b7de3f
Step 4/19 : RUN apt-get install -y build-essential
 ---> Using cache
 ---> 72444552d616
Step 5/19 : RUN apt-get install -y cmake
 ---> Using cache
 ---> 25504b73838e
Step 6/19 : RUN apt-get install -y python-dev
 ---> Using cache
 ---> fca9d71231f0
Step 7/19 : RUN apt-get install -y python-pip
 ---> Using cache
 ---> 17979ae5d0bd
Step 8/19 : RUN apt-get install -y python-imaging
 ---> Using cache
 ---> 40ea2b1efa7e
Step 9/19 : RUN apt-get install -y mc
 ---> Using cache
 ---> 36f5999d0ee1
Step 10/19 : RUN apt-get install -y nano
 ---> Using cache
 ---> 30b05b6ffc66
Step 11/19 : RUN pip install pip --upgrade
 ---> Using cache
 ---> 705fd9f31297
Step 12/19 : RUN pip install virtualenv
 ---> Using cache
 ---> 482d3b6446ed
Step 13/19 : RUN mkdir /backend
 ---> Using cache
 ---> 10ea407a46b1
Step 14/19 : WORKDIR /backend
 ---> Using cache
 ---> d31179b83392
Step 15/19 : ADD examples/requirements/ /backend/requirements/
 ---> Using cache
 ---> e71eb2cd8092
Step 16/19 : RUN pip install -r /backend/requirements/dev.txt
 ---> Using cache
 ---> 12f16504fd24
Step 17/19 : RUN pip install -r /backend/requirements/elastic_6x.txt
 ---> Using cache
 ---> 0bff9d59291b
Step 18/19 : COPY . /backend/
 ---> Using cache
 ---> 3bde5cbd94f7
Step 19/19 : RUN python /backend/setup.py develop
 ---> Using cache
 ---> 5f9da16762d1
Successfully built 5f9da16762d1
Successfully tagged django_elasticsearch_dsl_drf_backend:latest
Building frontend
Step 1/10 : FROM node:latest
 ---> 2824ef9be5b3
Step 2/10 : RUN apt-get update
 ---> Using cache
 ---> fed5213a0467
Step 3/10 : RUN apt-get install -y mc
 ---> Using cache
 ---> c84faa8025ec
Step 4/10 : RUN apt-get install -y nano
 ---> Using cache
 ---> 1c9c6217d399
Step 5/10 : RUN mkdir /frontend
 ---> Using cache
 ---> 0ff7d8d626d3
Step 6/10 : ADD examples/frontend/package.json /frontend/
 ---> Using cache
 ---> 11f86e5a45d0
Step 7/10 : ADD . /frontend/
 ---> Using cache
 ---> ded5fb74f2f0
Step 8/10 : WORKDIR /frontend
 ---> Using cache
 ---> 709fa88c2b1e
Step 9/10 : RUN yarn add kleur@latest
 ---> Using cache
 ---> 42251144c06e
Step 10/10 : RUN yarn
 ---> Using cache
 ---> 3690bafe9fbb
Successfully built 3690bafe9fbb
Successfully tagged django_elasticsearch_dsl_drf_frontend:latest
Recreating elasticsearch ... done
Recreating django_elasticsearch_dsl_drf_backend ... done
Recreating django_elasticsearch_dsl_drf_frontend ... done
Attaching to elasticsearch, django_elasticsearch_dsl_drf_backend, django_elasticsearch_dsl_drf_frontend
elasticsearch    | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
elasticsearch    | OpenJDK 64-Bit Server VM warning: UseAVX=2 is not supported on this CPU, setting it to UseAVX=1
django_elasticsearch_dsl_drf_backend | standard_init_linux.go:190: exec user process caused "no such file or directory"
django_elasticsearch_dsl_drf_backend exited with code 1
django_elasticsearch_dsl_drf_frontend | mesg: ttyname failed: Inappropriate ioctl for device
elasticsearch    | [2018-12-20T08:49:00,347][WARN ][o.e.b.JNANatives         ] Unable to lock JVM Memory: error=12, reason=Cannot allocate memory
elasticsearch    | [2018-12-20T08:49:00,369][WARN ][o.e.b.JNANatives         ] This can result in part of the JVM being swapped out.
elasticsearch    | [2018-12-20T08:49:00,369][WARN ][o.e.b.JNANatives         ] Increase RLIMIT_MEMLOCK, soft limit: 83968000, hard limit: 83968000
elasticsearch    | [2018-12-20T08:49:00,369][WARN ][o.e.b.JNANatives         ] These can be adjusted by modifying /etc/security/limits.conf, for example:
elasticsearch    |      # allow user 'elasticsearch' mlockall
elasticsearch    |      elasticsearch soft memlock unlimited
elasticsearch    |      elasticsearch hard memlock unlimited
elasticsearch    | [2018-12-20T08:49:00,370][WARN ][o.e.b.JNANatives         ] If you are logged in interactively, you will have to re-login for the new limits to take effect.
elasticsearch    | [2018-12-20T08:49:01,342][INFO ][o.e.n.Node               ] [] initializing ...
elasticsearch    | [2018-12-20T08:49:01,860][INFO ][o.e.e.NodeEnvironment    ] [8NsZMol] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/sda1)]], net usable_space [51.1gb], net total_space [58.4gb], types [ext4]
elasticsearch    | [2018-12-20T08:49:01,863][INFO ][o.e.e.NodeEnvironment    ] [8NsZMol] heap size [495.3mb], compressed ordinary object pointers [true]
elasticsearch    | [2018-12-20T08:49:01,865][INFO ][o.e.n.Node               ] [8NsZMol] node name derived from node ID [8NsZMolsRmykQw7-_Y-Btg]; set [node.name] to override
elasticsearch    | [2018-12-20T08:49:01,865][INFO ][o.e.n.Node               ] [8NsZMol] version[6.3.2], pid[1], build[default/tar/053779d/2018-07-20T05:20:23.451332Z], OS[Linux/4.9.125-linuxkit/amd64], JVM["Oracle Corporation"/OpenJDK 64-Bit Server VM/10.0.2/10.0.2+13]
elasticsearch    | [2018-12-20T08:49:01,866][INFO ][o.e.n.Node               ] [8NsZMol] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/tmp/elasticsearch.8Kvf64Bt, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Djava.locale.providers=COMPAT, -XX:UseAVX=2, -Des.cgroups.hierarchy.override=/, -Xms512m, -Xmx512m, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=tar]
django_elasticsearch_dsl_drf_frontend | yarn run v1.12.3
django_elasticsearch_dsl_drf_frontend | $ BROWSER=none react-scripts start
django_elasticsearch_dsl_drf_frontend | /bin/sh: 1: react-scripts: not found
django_elasticsearch_dsl_drf_frontend | error Command failed with exit code 127.
django_elasticsearch_dsl_drf_frontend | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
django_elasticsearch_dsl_drf_frontend exited with code 1
elasticsearch    | [2018-12-20T08:49:06,438][INFO ][o.e.p.PluginsService     ] [8NsZMol] loaded module [aggs-matrix-stats]
elasticsearch    | [2018-12-20T08:49:06,439][INFO ][o.e.p.PluginsService     ] [8NsZMol] loaded module [analysis-common]
elasticsearch    | [2018-12-20T08:49:06,439][INFO ][o.e.p.PluginsService     ] [8NsZMol] loaded module [ingest-common]
elasticsearch    | [2018-12-20T08:49:06,440][INFO ][o.e.p.PluginsService     ] [8NsZMol] loaded module [lang-expression]
elasticsearch    | [2018-12-20T08:49:06,440][INFO ][o.e.p.PluginsService     ] [8NsZMol] loaded module [lang-mustache]
elasticsearch    | [2018-12-20T08:49:06,440][INFO ][o.e.p.PluginsService     ] [8NsZMol] loaded module [lang-painless]
elasticsearch    | [2018-12-20T08:49:06,440][INFO ][o.e.p.PluginsService     ] [8NsZMol] loaded module [mapper-extras]
elasticsearch    | [2018-12-20T08:49:06,440][INFO ][o.e.p.PluginsService     ] [8NsZMol] loaded module [parent-join]
elasticsearch    | [2018-12-20T08:49:06,441][INFO ][o.e.p.PluginsService     ] [8NsZMol] loaded module [percolator]
elasticsearch    | [2018-12-20T08:49:06,441][INFO ][o.e.p.PluginsService     ] [8NsZMol] loaded module [rank-eval]
elasticsearch    | [2018-12-20T08:49:06,441][INFO ][o.e.p.PluginsService     ] [8NsZMol] loaded module [reindex]
elasticsearch    | [2018-12-20T08:49:06,442][INFO ][o.e.p.PluginsService     ] [8NsZMol] loaded module [repository-url]
elasticsearch    | [2018-12-20T08:49:06,442][INFO ][o.e.p.PluginsService     ] [8NsZMol] loaded module [transport-netty4]
elasticsearch    | [2018-12-20T08:49:06,442][INFO ][o.e.p.PluginsService     ] [8NsZMol] loaded module [tribe]
elasticsearch    | [2018-12-20T08:49:06,442][INFO ][o.e.p.PluginsService     ] [8NsZMol] loaded module [x-pack-core]
elasticsearch    | [2018-12-20T08:49:06,442][INFO ][o.e.p.PluginsService     ] [8NsZMol] loaded module [x-pack-deprecation]
elasticsearch    | [2018-12-20T08:49:06,443][INFO ][o.e.p.PluginsService     ] [8NsZMol] loaded module [x-pack-graph]
elasticsearch    | [2018-12-20T08:49:06,443][INFO ][o.e.p.PluginsService     ] [8NsZMol] loaded module [x-pack-logstash]
elasticsearch    | [2018-12-20T08:49:06,443][INFO ][o.e.p.PluginsService     ] [8NsZMol] loaded module [x-pack-ml]
elasticsearch    | [2018-12-20T08:49:06,443][INFO ][o.e.p.PluginsService     ] [8NsZMol] loaded module [x-pack-monitoring]
elasticsearch    | [2018-12-20T08:49:06,443][INFO ][o.e.p.PluginsService     ] [8NsZMol] loaded module [x-pack-rollup]
elasticsearch    | [2018-12-20T08:49:06,444][INFO ][o.e.p.PluginsService     ] [8NsZMol] loaded module [x-pack-security]dule [x-pack-security]                                                                            dule [x-pack-sql]
elasticsearch    | [2018-12-20T08:49:06,444][INFO ][o.e.p.PluginsService     ] [8NsZMol] loaded module [x-pack-upgrade]dule [x-pack-sql]                                                                                 dule [x-pack-watcher]
elasticsearch    | [2018-12-20T08:49:06,445][INFO ][o.e.p.PluginsService     ] [8NsZMol] loaded mougin [ingest-geoip]dule [x-pack-upgrade]                                                                             ugin [ingest-user-agent]
elasticsearch    | [2018-12-20T08:49:06,445][INFO ][o.e.p.PluginsService     ] [8NsZMol] loaded mor/82] [Main.cc@109] controller (64 bit): Version 6.3.2 (Build 903094f295d249) Copyright (c) 2018 Eladule [x-pack-watcher]
elasticsearch    | [2018-12-20T08:49:06,445][INFO ][o.e.p.PluginsService     ] [8NsZMol] loaded plcovery type [single-node]ugin [ingest-geoip]                                                                               ed
elasticsearch    | [2018-12-20T08:49:06,446][INFO ][o.e.p.PluginsService     ] [8NsZMol] loaded pl...ugin [ingest-user-agent]                                                                          ddress {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}
elasticsearch    | [2018-12-20T08:49:10,938][INFO ][o.e.x.m.j.p.l.CppLogMessageHandler] [controllecking requested for elasticsearch process but memory is not lockedr/82] [Main.cc@109] controller (64 bit): Version 6.3.2 (Build 903094f295d249) Copyright (c) 2018 Eublish_address {172.18.0.2:9200}, bound_addresses {0.0.0.0:9200}lasticsearch BV
elasticsearch    | [2018-12-20T08:49:11,781][INFO ][o.e.d.DiscoveryModule    ] [8NsZMol] using dis369742c1-ed24-4fa6-b5dd-88792fd1452a] mode [basic] - validcovery type [single-node]                                                                          [0] indices into cluster_state
elasticsearch    | [2018-12-20T08:49:12,904][INFO ][o.e.n.Node               ] [8NsZMol] initialized
elasticsearch    | [2018-12-20T08:49:12,919][INFO ][o.e.n.Node               ] [8NsZMol] starting
...
elasticsearch    | [2018-12-20T08:49:13,258][INFO ][o.e.t.TransportService   ] [8NsZMol] publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}
elasticsearch    | [2018-12-20T08:49:13,313][WARN ][o.e.b.BootstrapChecks    ] [8NsZMol] memory locking requested for elasticsearch process but memory is not locked
elasticsearch    | [2018-12-20T08:49:13,401][INFO ][o.e.h.n.Netty4HttpServerTransport] [8NsZMol] publish_address {172.18.0.2:9200}, bound_addresses {0.0.0.0:9200}
elasticsearch    | [2018-12-20T08:49:13,401][INFO ][o.e.n.Node               ] [8NsZMol] started
elasticsearch    | [2018-12-20T08:49:13,990][INFO ][o.e.l.LicenseService     ] [8NsZMol] license [369742c1-ed24-4fa6-b5dd-88792fd1452a] mode [basic] - valid
elasticsearch    | [2018-12-20T08:49:14,032][INFO ][o.e.g.GatewayService     ] [8NsZMol] recovered [0] indices into cluster_state

**Comment by barseghyanartur** [comment]
@infokani:

Thanks for bringing this up. I'll check it as soon as possible.

**Comment by clement-mwendwa** [comment]
Had a similar issue where I couldn't get the frontend running. After multiple builds and reruns, I was able to resolve it by running `yarn install` or ` npm install` in the host system.   Should this be part of the documentation? Optionally there can be a start script that does it for users.

**Comment by barseghyanartur** [comment]
@clement-mwendwa:

I don't think it's that, because it's already a part of the frontend [Dockerfile](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/docker/frontend/Dockerfile#L13).

**Comment by clement-mwendwa** [comment]
@barseghyanartur I saw that it's however not writing to the volume. If you do a fresh build the folder `node_modules` won't be there after the build is done. So could be something to do with the volumes. Check [this](https://stackoverflow.com/questions/48806626/docker-compose-run-yarn-install) out.

**Comment by infokani** [comment]
i think there is OS dependent some configuration. I run it on Windows 10 and worked only elasticsearch. In linux everything ok except one. In Linux elastic and backend up running but frontend not working. It seems not creating node_modules in desired directory.

**Comment by barseghyanartur** [comment]
@infokani, @clement-mwendwa:

Please, check the latest master. For me everything works fine.

Versions:

- Ubuntu: 16.04.
- Docker: 18.09.0, build 4d60db4

Please, tell me if it works for you now.

**Comment by clement-mwendwa** [comment]
Still fails on OS X 
```
django_elasticsearch_dsl_drf_frontend | /bin/sh: 1: react-scripts: not found
django_elasticsearch_dsl_drf_frontend | error Command failed with exit code 127.
django_elasticsearch_dsl_drf_frontend | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
django_elasticsearch_dsl_drf_frontend exited with code 1
```

**Comment by barseghyanartur** [comment]
@clement-mwendwa:

I don't have OS X. If you're using this package, could you try to solve the issue?

**Comment by infokani** [comment]
Problem 1: not creating node_modules
Solution: First build node_modules in examples/frontend directory before build docker image

Problem 2: OS specific configuration in backend 
Solution: Use linux

**Comment by clement-mwendwa** [comment]
@barseghyanartur, as noted above the current solution is to build the node modules in the directory before building the app with composing. The solution could be either adding this to the documentation, adding a script for building that does it or both. What's your take on this?

**Comment by barseghyanartur** [comment]
@clement-mwendwa:

I still don't clearly understand why it does not work (for me it does).

`npm install` inside the newly created container is a common practice. I don't want to step away from simplicity of the `docker-compose up --build`.

I would be grateful if someone could pick this issue up (preferably someone with a access to MacOS, since on my Linux installation with fresh repository clone it all works fine).

**Comment by clement-mwendwa** [comment]
@barseghyanartur  I can pick it up and dig deeper.

**Comment by barseghyanartur** [comment]
@clement-mwendwa: Please!

**Comment by barseghyanartur** [comment]
@infokani:

Please, check the latest master. It shall be working now. Let me know if it does work for you.

**Comment by bashu** [comment]
@barseghyanartur meh, got this while running `docker-compose up --build`:
```sh
  Downloading https://files.pythonhosted.org/packages/5c/1c/6997288da181277a0c29bc39a5f9143ff20b8c99f2a7d059cfb55163e165/psycopg2-2.8.3.tar.gz (377kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-07vnyftm/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-07vnyftm/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-07vnyftm/psycopg2/
    Complete output (23 lines):
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'

    Error: pg_config executable not found.

    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.

    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).

    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Service 'backend' failed to build: The command '/bin/sh -c pip install -r /backend/requirements/dev.txt' returned a non-zero code: 1
```

**Comment by minh92** [comment]
backend is not working for me, can you help me? I am using windows 10 and docker desktop community version 2.1.0.5 and I got this error:
django_elasticsearch_dsl_drf_backend | standard_init_linux.go:211: exec user process caused "no such file or directory"

can you pls help me to fix this problem?

**Comment by barseghyanartur** [comment]
``docker-compose up`` works for me now (just did fresh build). Please, let me know if something doesn't work for you.
